<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Untitled</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="cancerwork_tree_files/libs/clipboard/clipboard.min.js"></script>
<script src="cancerwork_tree_files/libs/quarto-html/quarto.js"></script>
<script src="cancerwork_tree_files/libs/quarto-html/popper.min.js"></script>
<script src="cancerwork_tree_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="cancerwork_tree_files/libs/quarto-html/anchor.min.js"></script>
<link href="cancerwork_tree_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="cancerwork_tree_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="cancerwork_tree_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="cancerwork_tree_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="cancerwork_tree_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Untitled</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="data-sets-created" class="level2">
<h2 class="anchored" data-anchor-id="data-sets-created">Data sets created</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>data_train <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"group_37.csv"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>data_test <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"arcene_test (for groups 32-38).csv"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(data_train))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(data_test))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ncol</span>(data_train) <span class="sc">==</span> </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>(<span class="fu">colnames</span>(data_train) <span class="sc">%in%</span> <span class="fu">colnames</span>(data_test))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>class <span class="ot">&lt;-</span> data_train[, <span class="dv">1</span>]</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>features <span class="ot">&lt;-</span> data_train[, <span class="sc">-</span><span class="dv">1</span>]</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>data_train[, <span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(data_train[, <span class="dv">1</span>] <span class="sc">==</span> <span class="sc">-</span><span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="initial-rejection-of-potential-probes" class="level2">
<h2 class="anchored" data-anchor-id="initial-rejection-of-potential-probes">Initial rejection of potential probes</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>feature_sd <span class="ot">&lt;-</span> <span class="fu">apply</span>(features, <span class="dv">2</span>, sd)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(feature_sd)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cancerwork_tree_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>q1 <span class="ot">&lt;-</span> <span class="fu">quantile</span>(feature_sd, <span class="fl">0.25</span>)  </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>q3 <span class="ot">&lt;-</span> <span class="fu">quantile</span>(feature_sd, <span class="fl">0.75</span>) </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>sd_threshold <span class="ot">&lt;-</span> q3<span class="sc">-</span>q1</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>selected_features <span class="ot">&lt;-</span> features[, feature_sd <span class="sc">&gt;</span> sd_threshold]</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>removed_features <span class="ot">&lt;-</span> features[, feature_sd <span class="sc">&lt;=</span> sd_threshold]</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"remaing features"</span>, <span class="fu">ncol</span>(selected_features), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>remaing features 1824 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"removed features:"</span>, <span class="fu">ncol</span>(removed_features), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>removed features: 3176 </code></pre>
</div>
</div>
</section>
<section id="data-dimension-reduction-processing" class="level2">
<h2 class="anchored" data-anchor-id="data-dimension-reduction-processing">Data Dimension Reduction Processing</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co">#use PCA</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>pca<span class="ot">&lt;-</span><span class="fu">prcomp</span>(selected_features)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>sd.pca <span class="ot">&lt;-</span> pca<span class="sc">$</span>sdev</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="co">#based on kaiser</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>tot.var<span class="ot">&lt;-</span><span class="fu">sum</span>(sd.pca<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>ave.var<span class="ot">&lt;-</span>tot.var<span class="sc">/</span><span class="fu">ncol</span>(selected_features)</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>ave.var </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 18507.17</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>sd.pca<span class="sc">^</span><span class="dv">2</span> <span class="sc">&gt;</span> ave.var</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [13]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [25]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [37]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
 [49] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [61] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [73] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [85] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [97] FALSE FALSE FALSE FALSE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>all_variance <span class="ot">&lt;-</span> sd.pca<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>cum_variance <span class="ot">&lt;-</span> <span class="fu">cumsum</span>(all_variance) <span class="sc">/</span> <span class="fu">sum</span>(all_variance)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>selected_components <span class="ot">&lt;-</span> <span class="fu">which</span>(sd.pca<span class="sc">^</span><span class="dv">2</span> <span class="sc">&gt;</span> ave.var)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>selected_variance <span class="ot">&lt;-</span> <span class="fu">sum</span>(all_variance[selected_components]) <span class="sc">/</span> <span class="fu">sum</span>(all_variance)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Cumulative contribution:"</span>, selected_variance, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Cumulative contribution: 0.9880857 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>pca_features1 <span class="ot">&lt;-</span> pca<span class="sc">$</span>x[, <span class="dv">1</span><span class="sc">:</span><span class="dv">47</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co">#based on Cumulative variance contribution 95%</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>cumulative_variance <span class="ot">&lt;-</span> <span class="fu">cumsum</span>(sd.pca<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> <span class="fu">sum</span>(sd.pca<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>selected_components_cumulative <span class="ot">&lt;-</span> <span class="fu">which</span>(cumulative_variance <span class="sc">&gt;=</span> <span class="fl">0.95</span>)[<span class="dv">1</span>]</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>selected_components_cumulative</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 18</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>pca_features2 <span class="ot">&lt;-</span> pca<span class="sc">$</span>x[, <span class="dv">1</span><span class="sc">:</span>selected_components_cumulative]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>traindata <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(pca_features1, <span class="at">Class =</span> data_train[[<span class="dv">1</span>]])</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>data_train<span class="sc">$</span>Class<span class="ot">&lt;-</span> <span class="fu">as.factor</span>(data_train<span class="sc">$</span>Class)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(traindata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   100 obs. of  48 variables:
 $ PC1  : num  -4922 -4850 -5391 -4335 950 ...
 $ PC2  : num  826 1308 900 1303 -5316 ...
 $ PC3  : num  -321 186 -720 539 139 ...
 $ PC4  : num  -49.4 209.4 211.1 -360.5 -97.9 ...
 $ PC5  : num  1089 -1458 562 -204 214 ...
 $ PC6  : num  369 -1252 112 -104 142 ...
 $ PC7  : num  -1191 688 -657 -921 -131 ...
 $ PC8  : num  37.7 -441.8 143.2 -116.4 -189.6 ...
 $ PC9  : num  -107 740 345 -236 -524 ...
 $ PC10 : num  715 -407 531 1018 -51 ...
 $ PC11 : num  -382 -145 -485 396 -295 ...
 $ PC12 : num  246.3 -286.5 -20.8 964.4 -343.7 ...
 $ PC13 : num  -324.6 34.2 219.3 -827.4 -94.9 ...
 $ PC14 : num  203 149 257 -651 -472 ...
 $ PC15 : num  -308.5 -132.8 -403.6 -134.4 -65.3 ...
 $ PC16 : num  56.1 127.8 -132.8 221.5 -421.2 ...
 $ PC17 : num  -302.01 -224.58 466.17 -910.23 -6.05 ...
 $ PC18 : num  -68.3 -158 -73.9 86.6 -915.5 ...
 $ PC19 : num  327 363 -317 320 387 ...
 $ PC20 : num  -74.9 225.8 -288.8 153.8 -507.9 ...
 $ PC21 : num  379.87 189.4 -9.57 156.48 -464.19 ...
 $ PC22 : num  -9.96 -130.53 -133 -160.89 -209.59 ...
 $ PC23 : num  30.9 244.1 -113.4 312.6 10.2 ...
 $ PC24 : num  -17.1 -263.3 11.1 -97.9 -187.9 ...
 $ PC25 : num  142.1 46.2 -76.9 -10.3 -158.3 ...
 $ PC26 : num  -68.4 -238.2 108.6 163 412.1 ...
 $ PC27 : num  24.8 96.4 224.8 -173.2 -339.9 ...
 $ PC28 : num  -136.38 -169.1 -7.89 -78.82 -292.1 ...
 $ PC29 : num  149.539 -0.688 305.624 48.26 86.191 ...
 $ PC30 : num  -67 -78.7 -106.8 -252.5 442.4 ...
 $ PC31 : num  12.51 -249.88 -83.46 3.57 108.15 ...
 $ PC32 : num  30.3 -6.9 -36.3 -265.3 43.2 ...
 $ PC33 : num  -254.2 -158.6 88.4 -124 -432 ...
 $ PC34 : num  37.9 46.6 145.4 -190.8 177.6 ...
 $ PC35 : num  -211.4 64.2 202.6 -65.3 -250.6 ...
 $ PC36 : num  -11.8 83.4 -57.8 -164.8 -109.2 ...
 $ PC37 : num  -55.5 243.9 180.8 -124.9 185.9 ...
 $ PC38 : num  88.7 -37.6 71.9 133.7 -92 ...
 $ PC39 : num  118.6 -40.1 -151.8 68.6 177.7 ...
 $ PC40 : num  -134.4 -274.3 -33 -87.6 126.9 ...
 $ PC41 : num  -96.7 29.6 -12.6 162.9 -22.3 ...
 $ PC42 : num  181 16 -149 103 -126 ...
 $ PC43 : num  134 -163 112 -158 -102 ...
 $ PC44 : num  207.7 195.3 -271.1 52.1 -48.3 ...
 $ PC45 : num  -191.8 20 21.2 309.5 -287.5 ...
 $ PC46 : num  -120.11 150.88 74.98 -2.49 -57.45 ...
 $ PC47 : num  88.6 -74 75.9 37.4 -119.8 ...
 $ Class: num  1 0 1 1 0 0 1 0 0 0 ...</code></pre>
</div>
</div>
</section>
<section id="tree-based-methods" class="level2">
<h2 class="anchored" data-anchor-id="tree-based-methods">Tree-based methods</h2>
<section id="classification-tree" class="level3">
<h3 class="anchored" data-anchor-id="classification-tree">Classification Tree</h3>
<p>Description: Classification Tree partition the feature space into a number of disjoint and non-overlapping regions. And predict the class of a given observation as the most commonly occurring class of training observations is the region to which it belongs.<span class="citation" data-cites="week4_tree_based">(<a href="#ref-week4_tree_based" role="doc-biblioref">Instructor 2025</a>)</span></p>
<p>Reason: it’s easy to understand and handle the categorical features without the need to create a long series of dummy variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co">#classification</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rpart)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rpart.plot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'rpart.plot' was built under R version 4.4.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2023</span>)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>model.classification <span class="ot">&lt;-</span> <span class="fu">rpart</span>(Class<span class="sc">~</span>.,<span class="at">data=</span>traindata,<span class="at">method=</span><span class="st">"class"</span>,<span class="at">cp=</span><span class="sc">-</span><span class="dv">1</span>,<span class="at">minsplit=</span><span class="dv">2</span>,<span class="at">minbucket=</span><span class="dv">1</span>)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="fu">printcp</span>(model.classification)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Classification tree:
rpart(formula = Class ~ ., data = traindata, method = "class", 
    cp = -1, minsplit = 2, minbucket = 1)

Variables actually used in tree construction:
[1] PC1  PC10 PC12 PC13 PC19 PC29 PC31 PC32

Root node error: 44/100 = 0.44

n= 100 

         CP nsplit rel error  xerror     xstd
1  0.340909      0  1.000000 1.00000 0.112815
2  0.159091      1  0.659091 0.81818 0.109091
3  0.125000      2  0.500000 0.72727 0.106017
4  0.068182      4  0.250000 0.65909 0.103128
5  0.045455      6  0.113636 0.63636 0.102045
6  0.022727      7  0.068182 0.54545 0.097064
7  0.011364      9  0.022727 0.61364 0.100900
8 -1.000000     11  0.000000 0.61364 0.100900</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotcp</span>(model.classification)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in sqrt(cp0 * c(Inf, cp0[-length(cp0)])): NaNs produced</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cancerwork_tree_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Start with a tree is fully grown, to see the cross validation results use the printcp() function and use plotcp() function to check the complexity parameter value. The smallest tree strategy refers to the largest cp value which is under the dashed line; the intercept of this line equals to the minimum xerror plus its standard deviation 0.642514(0.54545+ 0.097064). Check the table, the value in the range of (0.045455, 0.068182), from the cp plot, the table should larger than 0.642514. So use the cp is 0.032 to prune the tree.</p>
<section id="pruning-a-tree" class="level4">
<h4 class="anchored" data-anchor-id="pruning-a-tree">Pruning a tree</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>model.classification <span class="ot">&lt;-</span> <span class="fu">prune</span>(model.classification,<span class="at">cp=</span><span class="fl">0.032</span>)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>model.classification</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>n= 100 

node), split, n, loss, yval, (yprob)
      * denotes terminal node

 1) root 100 44 0 (0.56000000 0.44000000)  
   2) PC1&gt;=1107.183 49 11 0 (0.77551020 0.22448980)  
     4) PC12&gt;=-211.8816 36  1 0 (0.97222222 0.02777778) *
     5) PC12&lt; -211.8816 13  3 1 (0.23076923 0.76923077)  
      10) PC13&gt;=659.5586 3  0 0 (1.00000000 0.00000000) *
      11) PC13&lt; 659.5586 10  0 1 (0.00000000 1.00000000) *
   3) PC1&lt; 1107.183 51 18 1 (0.35294118 0.64705882)  
     6) PC1&lt; -4681.885 27 11 0 (0.59259259 0.40740741)  
      12) PC29&lt; 145.1306 21  5 0 (0.76190476 0.23809524)  
        24) PC31&lt; 182.5574 18  2 0 (0.88888889 0.11111111) *
        25) PC31&gt;=182.5574 3  0 1 (0.00000000 1.00000000) *
      13) PC29&gt;=145.1306 6  0 1 (0.00000000 1.00000000) *
     7) PC1&gt;=-4681.885 24  2 1 (0.08333333 0.91666667)  
      14) PC19&gt;=353.6153 2  0 0 (1.00000000 0.00000000) *
      15) PC19&lt; 353.6153 22  0 1 (0.00000000 1.00000000) *</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rpart.plot</span>(model.classification,<span class="at">type =</span> <span class="dv">2</span>,<span class="at">extra =</span> <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cancerwork_tree_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>After pruning trees with cp =0.032. Check the plot of tree, the variable where the split happens are PC1, PC12, PC13,PC29,PC19,PC31. The terminal nodes of the tree with the 1 as the predicted class have a high probability and the terminal nodes of the tree with 0(-1) as the predicted class have a high probability.</p>
</section>
<section id="variable-importance" class="level4">
<h4 class="anchored" data-anchor-id="variable-importance">Variable Importance</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>model.classification<span class="sc">$</span>variable.importance</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       PC1       PC12        PC2       PC18       PC13        PC4       PC45 
15.5150718 13.0512977 12.2892861  8.5209284  7.7116945  7.0165055  5.5003220 
      PC19       PC29       PC11       PC17       PC31       PC25        PC7 
 5.4726631  5.4179894  5.4031409  4.6153846  4.0634921  3.2311986  3.2311986 
      PC43        PC8        PC5       PC15       PC27       PC10       PC22 
 3.0769231  2.9141740  2.7460058  2.7089947  2.7089947  2.7089947  1.6155993 
      PC16        PC9       PC20       PC21       PC24 
 1.3544974  1.3544974  0.9029982  0.9029982  0.9029982 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(model.classification<span class="sc">$</span>variable.importance,<span class="at">col=</span><span class="st">"lightpink"</span>,<span class="at">main =</span> <span class="st">"variable Importance"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cancerwork_tree_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>According to the classification tree, PC1 is the most important factor, followed by PC12 and PC2, then the PC18 and PC13, PC21 and PC24 are relatively unimportant.</p>
</section>
<section id="roc-and-auc" class="level4">
<h4 class="anchored" data-anchor-id="roc-and-auc">ROC and AUC:</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>data_test[, <span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(data_test[, <span class="dv">1</span>] <span class="sc">==</span> <span class="sc">-</span><span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>selected_features_names <span class="ot">&lt;-</span> <span class="fu">colnames</span>(selected_features)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>data_test_new <span class="ot">&lt;-</span> data_test[, selected_features_names]</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>testdata <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>              <span class="fu">predict</span>(pca, <span class="at">newdata =</span> data_test_new)[,<span class="dv">1</span><span class="sc">:</span><span class="dv">47</span>],</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">Class =</span> data_test[[<span class="dv">1</span>]])</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(testdata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   100 obs. of  48 variables:
 $ PC1  : num  -4765 599 4605 -5169 -4091 ...
 $ PC2  : num  1103 1303 2403 1102 1382 ...
 $ PC3  : num  -233 -4171 -500 309 1033 ...
 $ PC4  : num  490 2101 -1864 138 -855 ...
 $ PC5  : num  -1320.9 1917.6 -396.4 -314.6 12.7 ...
 $ PC6  : num  -441 -584.7 84.1 -374.2 476.5 ...
 $ PC7  : num  284 799 -367 290 -366 ...
 $ PC8  : num  -739 854 -1090 179 -483 ...
 $ PC9  : num  859.3 1047.8 -471.1 28.8 -804.9 ...
 $ PC10 : num  845.7 -374.8 58.3 -1009.8 390.6 ...
 $ PC11 : num  39.6 907.1 -276.6 -267.3 1043.4 ...
 $ PC12 : num  305 -250 -144 -634 716 ...
 $ PC13 : num  644 654 708 -152 -133 ...
 $ PC14 : num  -369 -339 149 373 422 ...
 $ PC15 : num  972.9 -226.4 89.5 -354 980.8 ...
 $ PC16 : num  -179.3 -704.4 321.8 82.6 340.5 ...
 $ PC17 : num  244.4 -348.7 36.4 20.8 -480.9 ...
 $ PC18 : num  243.73 8.3 -261.93 -4.29 71.23 ...
 $ PC19 : num  227 -380 271 174 -125 ...
 $ PC20 : num  -392.9 36.7 12.5 -168.7 -581.2 ...
 $ PC21 : num  299.83 412.93 146.68 -234.53 -5.51 ...
 $ PC22 : num  262.9 699.4 456.2 -55.8 315 ...
 $ PC23 : num  183.22 -493.79 69.82 -270.25 -3.26 ...
 $ PC24 : num  173.5 -97.3 15.5 79.3 539.1 ...
 $ PC25 : num  125 456 234 -129 164 ...
 $ PC26 : num  -586.2 899.5 28.9 67.2 -33.7 ...
 $ PC27 : num  118.8 43 -89.6 -106.3 -84.3 ...
 $ PC28 : num  -160.3 -176.8 -245.7 79.5 -43.6 ...
 $ PC29 : num  -79 138.7 -239 73.7 -39.1 ...
 $ PC30 : num  -19.7 160.6 33.7 56.7 40.7 ...
 $ PC31 : num  -262.4 -223.7 -143.9 -16.7 113.9 ...
 $ PC32 : num  341 338 325 -103 -102 ...
 $ PC33 : num  -110 422.8 396.2 116.4 -85.2 ...
 $ PC34 : num  110.79 221.8 155.08 -283.26 9.88 ...
 $ PC35 : num  -320 -226 210 281 142 ...
 $ PC36 : num  42.3 -76.8 117.8 -194.3 -240.8 ...
 $ PC37 : num  407.1 135.5 -197.4 -92.2 99.5 ...
 $ PC38 : num  25.9 99.1 -107.3 150.5 -155.1 ...
 $ PC39 : num  -209.78 -135.41 1.33 -131.76 -133.89 ...
 $ PC40 : num  -11 -257.4 25.6 135.3 -95.7 ...
 $ PC41 : num  -19.1 -202.6 150.6 -53.8 31.5 ...
 $ PC42 : num  184.3 -73.6 -88.1 -45.8 -84.1 ...
 $ PC43 : num  117 -308 180 -107 -73 ...
 $ PC44 : num  214.37 -2.29 160.08 32.19 203.95 ...
 $ PC45 : num  -62.6 95.8 119.8 -13.7 182.5 ...
 $ PC46 : num  -136 -219.4 14.3 163.2 161.8 ...
 $ PC47 : num  32 -185 27.6 97.9 -75.6 ...
 $ Class: num  0 0 0 1 1 1 0 1 0 0 ...</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ROCR)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ROCR' was built under R version 4.4.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>pred.prob <span class="ot">&lt;-</span> <span class="fu">predict</span>(model.classification,<span class="at">newdata =</span> testdata,<span class="at">type =</span> <span class="st">"prob"</span>)[,<span class="dv">2</span>]</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>true_labels <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">as.character</span>(testdata<span class="sc">$</span>Class))</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>true_labels[true_labels <span class="sc">==</span> <span class="sc">-</span><span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>score2 <span class="ot">&lt;-</span> <span class="fu">prediction</span>(pred.prob,true_labels)</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>perf2 <span class="ot">&lt;-</span> <span class="fu">performance</span>(score2,<span class="st">"tpr"</span>,<span class="st">"fpr"</span>)</span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>auc2 <span class="ot">&lt;-</span> <span class="fu">performance</span>(score2,<span class="st">"auc"</span>)</span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>perfd2 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x=</span>perf2<span class="sc">@</span>x.values[<span class="dv">1</span>][[<span class="dv">1</span>]],<span class="at">y=</span>perf2<span class="sc">@</span>y.values[<span class="dv">1</span>][[<span class="dv">1</span>]])</span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(perfd2,<span class="fu">aes</span>(<span class="at">x=</span>x,<span class="at">y=</span>y))<span class="sc">+</span><span class="fu">geom_line</span>()<span class="sc">+</span></span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"False positive rate"</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">"True positive rate"</span>) <span class="sc">+</span></span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="fu">paste</span>(<span class="st">"Area under the curve:"</span>, <span class="fu">round</span>(auc2<span class="sc">@</span>y.values[[<span class="dv">1</span>]], <span class="dv">3</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cancerwork_tree_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The ROC curve show the classification performance. A higher AUC(close to 1 ) indicates a better-performing model. The AUC of classification tree is 0.694, which is greater than 0.5, show the classification effect is fair.</p>
<p>Prediction:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>class.pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(model.classification,<span class="at">newdata =</span> testdata,<span class="at">type=</span><span class="st">"class"</span>)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>test.table.class <span class="ot">&lt;-</span> <span class="fu">table</span>(testdata<span class="sc">$</span>Class,class.pred)</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(test.table.class)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   class.pred
     0  1
  0 38 18
  1 14 30</code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>accuracy <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">diag</span>(test.table.class))<span class="sc">/</span><span class="fu">sum</span>(test.table.class)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(accuracy)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.68</code></pre>
</div>
</div>
<p>After the predict of the test set, obtained the Confusion Matrix and the Accuracy. The Accuracy of test set is 0.68, which is poor. The classification tree model has some classification ability, but it is not particularly good.</p>
</section>
</section>
<section id="bagging-forest" class="level3">
<h3 class="anchored" data-anchor-id="bagging-forest">Bagging Forest</h3>
<p>Description: Repeatedly draw samples from the original dataset and build a classification tree on each bootstrapped sample. For a given test observation, record the class predicted from each tree and take a majority vote: the overall prediction is the most commonly occurring class across all the predictions.</p>
<p>Reason: Reduce the overfitting risk of a single tree, improve the stability and performance of the model. Can automatically adjust feature importance and easy to explain.</p>
<p>Set the dataset after the feature selection:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>traindata2 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(selected_features,<span class="at">Class =</span> data_train[<span class="dv">1</span>])</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>testdata2 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(data_test_new,<span class="at">Class =</span> data_test[<span class="dv">1</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(randomForest)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'randomForest' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>randomForest 4.7-1.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Type rfNews() to see new features/changes/bug fixes.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'randomForest'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:ggplot2':

    margin</code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co">#bagging</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2023</span>)</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>Model.bagging <span class="ot">&lt;-</span> <span class="fu">randomForest</span>(Class<span class="sc">~</span>.,<span class="at">data=</span>traindata2,<span class="at">mtry=</span><span class="fu">ncol</span>(traindata2)<span class="sc">-</span><span class="dv">1</span>,<span class="at">ntree=</span><span class="dv">500</span>)</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>Model.bagging</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
 randomForest(formula = Class ~ ., data = traindata2, mtry = ncol(traindata2) -      1, ntree = 500) 
               Type of random forest: classification
                     Number of trees: 500
No. of variables tried at each split: 1824

        OOB estimate of  error rate: 19%
Confusion matrix:
   0  1 class.error
0 47  9   0.1607143
1 10 34   0.2272727</code></pre>
</div>
</div>
<p>Start with randomForest() function and specify that the number of variables tried at each split,mtry,should be equal to the number of variables in the model. Set the ntree= 500, check the out-of-bag estimate of error rate.</p>
<section id="oob" class="level4">
<h4 class="anchored" data-anchor-id="oob">OOB:</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Model.bagging<span class="sc">$</span>err.rate[,<span class="dv">1</span>],<span class="at">type =</span> <span class="st">"l"</span>,</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Number of trees"</span>,<span class="at">ylab=</span><span class="st">"OOB Error"</span>,<span class="at">main=</span><span class="st">"OBB Error vs. Number of Trees"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cancerwork_tree_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>According to the graph, in the range of (200,500), the OOB error starts to stabilize after decreasing. Select the minimum number of trees that can stabilize the OBB error, there choose ntree = 200.</p>
<p>New model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2023</span>)</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>Model.bagging <span class="ot">&lt;-</span> <span class="fu">randomForest</span>(Class<span class="sc">~</span>.,<span class="at">data=</span>traindata2,<span class="at">mtry=</span><span class="fu">ncol</span>(traindata2)<span class="sc">-</span><span class="dv">1</span>,<span class="at">ntree=</span><span class="dv">200</span>)</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>Model.bagging</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
 randomForest(formula = Class ~ ., data = traindata2, mtry = ncol(traindata2) -      1, ntree = 200) 
               Type of random forest: classification
                     Number of trees: 200
No. of variables tried at each split: 1824

        OOB estimate of  error rate: 19%
Confusion matrix:
   0  1 class.error
0 47  9   0.1607143
1 10 34   0.2272727</code></pre>
</div>
</div>
<p>Building a new bagging forest model with ntree =200.</p>
</section>
<section id="variable-importance-1" class="level4">
<h4 class="anchored" data-anchor-id="variable-importance-1">Variable Importance:</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">importance</span>(Model.bagging)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               MeanDecreaseGini
Variable.6          0.000000000
Variable.7          0.086780836
Variable.15         0.009473684
Variable.16         0.000000000
Variable.25         0.059670846
Variable.29         0.000000000
Variable.40         0.000000000
Variable.43         0.000000000
Variable.45         0.026754297
Variable.69         0.000000000
Variable.83         0.008571429
Variable.103        0.000000000
Variable.107        0.061921513
Variable.108        0.000000000
Variable.109        0.000000000
Variable.113        0.000000000
Variable.118        0.000000000
Variable.132        1.545897188
Variable.143        0.000000000
Variable.153        0.110185212
Variable.168        0.100803160
Variable.172        0.000000000
Variable.193        0.000000000
Variable.202        0.000000000
Variable.211        0.000000000
Variable.214        0.006666667
Variable.215        0.000000000
Variable.218        0.073455460
Variable.258        0.000000000
Variable.261        0.000000000
Variable.263        0.000000000
Variable.281        0.625924772
Variable.294        0.000000000
Variable.301        0.051627907
Variable.312        0.019298246
Variable.325        0.000000000
Variable.327        0.000000000
Variable.331        0.017767442
Variable.332        0.000000000
Variable.345        0.000000000
Variable.346        0.049714286
Variable.363        0.000000000
Variable.370        0.032968816
Variable.381        0.000000000
Variable.382        0.000000000
Variable.392        0.009750000
Variable.398        0.035897436
Variable.400        0.000000000
Variable.403        0.000000000
Variable.409        0.017909357
Variable.414        0.015000000
Variable.426        0.000000000
Variable.430        0.019069767
Variable.433        0.000000000
Variable.456        0.000000000
Variable.457        0.009722222
Variable.471        0.366677066
Variable.474        0.000000000
Variable.484        0.018620690
Variable.496        0.000000000
Variable.498        0.037083744
Variable.501        0.000000000
Variable.507        0.026384615
Variable.508        0.035802714
Variable.521        0.007500000
Variable.540        0.047946429
Variable.549        0.009767442
Variable.577        0.000000000
Variable.600        0.000000000
Variable.613        0.000000000
Variable.636        0.000000000
Variable.640        0.000000000
Variable.643        0.000000000
Variable.659        0.000000000
Variable.661        0.000000000
Variable.664        0.016571429
Variable.686        0.051130580
Variable.701        0.094903753
Variable.717        0.000000000
Variable.732        0.008000000
Variable.746        0.000000000
Variable.768        0.163978152
Variable.775        0.053864799
Variable.806        0.000000000
Variable.827        0.000000000
Variable.830        0.101668890
Variable.835        0.000000000
Variable.840        0.000000000
Variable.844        0.009807692
Variable.847        0.061849267
Variable.848        0.000000000
Variable.857        0.031342342
Variable.858        0.146713928
Variable.868        0.047927928
Variable.887        0.000000000
Variable.908        0.000000000
Variable.911        0.027283217
Variable.913        0.000000000
Variable.919        0.000000000
Variable.926        0.000000000
Variable.934        0.000000000
Variable.941        0.032666667
Variable.949        0.006666667
Variable.951        0.000000000
Variable.954        0.000000000
Variable.982        0.015555556
Variable.995        0.016363636
Variable.1001       0.000000000
Variable.1016       0.000000000
Variable.1022       0.000000000
Variable.1023       0.000000000
Variable.1038       0.043586356
Variable.1043       0.035000000
Variable.1057       0.000000000
Variable.1059       0.000000000
Variable.1067       0.000000000
Variable.1070       0.000000000
Variable.1085       0.070473383
Variable.1093       0.000000000
Variable.1096       0.000000000
Variable.1105       0.000000000
Variable.1112       0.000000000
Variable.1127       0.015555556
Variable.1131       0.000000000
Variable.1132       0.000000000
Variable.1135       0.000000000
Variable.1137       0.018947368
Variable.1142       0.000000000
Variable.1146       0.000000000
Variable.1148       0.024375000
Variable.1149       0.000000000
Variable.1154       0.000000000
Variable.1169       0.000000000
Variable.1172       0.007500000
Variable.1181       0.000000000
Variable.1193       1.121540714
Variable.1194       0.000000000
Variable.1204       0.077786843
Variable.1223       0.000000000
Variable.1231       0.000000000
Variable.1235       0.238654096
Variable.1236       0.000000000
Variable.1239       0.000000000
Variable.1242       0.000000000
Variable.1251       0.008333333
Variable.1257       0.000000000
Variable.1260       0.000000000
Variable.1262       0.000000000
Variable.1263       0.000000000
Variable.1271       0.000000000
Variable.1285       0.000000000
Variable.1288       0.000000000
Variable.1297       0.000000000
Variable.1310       0.000000000
Variable.1311       0.044606061
Variable.1342       0.000000000
Variable.1367       0.009447939
Variable.1374       0.000000000
Variable.1379       0.000000000
Variable.1390       0.000000000
Variable.1391       0.023888889
Variable.1395       0.000000000
Variable.1400       0.189915959
Variable.1402       0.000000000
Variable.1407       0.000000000
Variable.1409       0.000000000
Variable.1411       0.086382813
Variable.1413       0.000000000
Variable.1419       0.035750000
Variable.1438       0.000000000
Variable.1449       0.008571429
Variable.1454       0.027863539
Variable.1455       0.298633047
Variable.1462       0.037032967
Variable.1463       0.000000000
Variable.1464       0.000000000
Variable.1466       0.027631579
Variable.1494       0.000000000
Variable.1496       0.048695652
Variable.1499       0.021000000
Variable.1500       0.000000000
Variable.1508       0.000000000
Variable.1510       0.055029762
Variable.1512       0.049146833
Variable.1513       0.066730159
Variable.1516       0.009714286
Variable.1530       0.000000000
Variable.1531       0.000000000
Variable.1556       0.000000000
Variable.1567       0.000000000
Variable.1591       0.015555556
Variable.1597       0.000000000
Variable.1603       0.061677632
Variable.1616       0.009615385
Variable.1619       0.000000000
Variable.1634       0.000000000
Variable.1649       0.000000000
Variable.1654       0.021224599
Variable.1660       0.000000000
Variable.1661       0.050084586
Variable.1671       0.000000000
Variable.1673       0.000000000
Variable.1674       0.026476998
Variable.1675       0.000000000
Variable.1680       0.016363636
Variable.1682       0.000000000
Variable.1702       0.009824561
Variable.1711       0.000000000
Variable.1721       0.000000000
Variable.1730       0.000000000
Variable.1736       0.000000000
Variable.1746       0.000000000
Variable.1768       0.000000000
Variable.1779       0.000000000
Variable.1805       0.000000000
Variable.1823       0.000000000
Variable.1824       0.000000000
Variable.1830       0.000000000
Variable.1832       0.086700000
Variable.1835       0.000000000
Variable.1849       0.000000000
Variable.1850       0.000000000
Variable.1870       0.000000000
Variable.1915       0.000000000
Variable.1919       0.026250000
Variable.1925       0.008888889
Variable.1936       0.280862610
Variable.1937       0.000000000
Variable.1967       0.000000000
Variable.1990       0.000000000
Variable.1992       0.015555556
Variable.2000       0.000000000
Variable.2005       0.000000000
Variable.2020       0.000000000
Variable.2022       0.570463443
Variable.2026       0.000000000
Variable.2040       0.000000000
Variable.2045       0.000000000
Variable.2057       0.000000000
Variable.2061       0.000000000
Variable.2071       0.019636364
Variable.2072       0.000000000
Variable.2077       0.056096711
Variable.2087       0.083573145
Variable.2097       0.000000000
Variable.2099       0.016000000
Variable.2101       0.016363636
Variable.2106       0.000000000
Variable.2107       0.000000000
Variable.2121       0.000000000
Variable.2126       0.026474359
Variable.2128       0.006666667
Variable.2146       0.000000000
Variable.2155       0.000000000
Variable.2174       0.000000000
Variable.2180       0.068383046
Variable.2190       0.160414212
Variable.2199       0.009756098
Variable.2216       0.075644493
Variable.2234       0.000000000
Variable.2243       0.000000000
Variable.2247       0.112520908
Variable.2280       0.000000000
Variable.2283       0.045835544
Variable.2284       0.000000000
Variable.2294       0.019200000
Variable.2297       0.008000000
Variable.2309       0.000000000
Variable.2325       0.000000000
Variable.2334       0.000000000
Variable.2348       0.070397354
Variable.2351       0.027233115
Variable.2357       0.000000000
Variable.2361       0.000000000
Variable.2364       0.000000000
Variable.2365       0.000000000
Variable.2373       0.046491764
Variable.2432       0.000000000
Variable.2442       0.000000000
Variable.2503       0.040000000
Variable.2506       0.000000000
Variable.2510       0.000000000
Variable.2517       0.031500000
Variable.2519       0.000000000
Variable.2525       0.032000000
Variable.2528       0.000000000
Variable.2534       0.000000000
Variable.2539       0.000000000
Variable.2542       0.000000000
Variable.2556       0.391066236
Variable.2557       0.000000000
Variable.2562       0.000000000
Variable.2575       0.000000000
Variable.2577       0.000000000
Variable.2583       0.000000000
Variable.2591       0.000000000
Variable.2605       0.008888889
Variable.2608       0.067141414
Variable.2629       0.188438029
Variable.2640       2.891559492
Variable.2644       0.000000000
Variable.2648       0.000000000
Variable.2652       0.101600905
Variable.2655       0.041256367
Variable.2658       0.000000000
Variable.2683       0.000000000
Variable.2684       0.000000000
Variable.2688       0.000000000
Variable.2690       0.000000000
Variable.2694       0.000000000
Variable.2706       0.000000000
Variable.2710       0.000000000
Variable.2737       0.000000000
Variable.2744       0.038912037
Variable.2748       0.000000000
Variable.2752       0.026952085
Variable.2753       0.000000000
Variable.2763       0.000000000
Variable.2777       0.000000000
Variable.2789       0.235841896
Variable.2798       0.000000000
Variable.2801       0.019130435
Variable.2807       0.000000000
Variable.2809       0.000000000
Variable.2816       0.043036053
Variable.2817       0.000000000
Variable.2818       0.000000000
Variable.2842       0.000000000
Variable.2854       0.000000000
Variable.2862       0.008333333
Variable.2866       0.000000000
Variable.2878       0.108991093
Variable.2895       0.000000000
Variable.2902       0.000000000
Variable.2905       0.027906977
Variable.2907       0.000000000
Variable.2914       0.000000000
Variable.2928       0.000000000
Variable.2929       0.000000000
Variable.2933       0.018232558
Variable.2945       0.000000000
Variable.2952       0.000000000
Variable.2956       0.061448505
Variable.2957       0.008000000
Variable.2958       0.000000000
Variable.2968       0.000000000
Variable.2980       0.020131579
Variable.2989       0.000000000
Variable.3010       0.000000000
Variable.3012       0.000000000
Variable.3017       0.000000000
Variable.3026       0.000000000
Variable.3036       0.034307329
Variable.3073       0.000000000
Variable.3075       0.000000000
Variable.3083       0.028886532
Variable.3091       0.000000000
Variable.3100       0.044915686
Variable.3111       0.000000000
Variable.3115       0.000000000
Variable.3125       0.000000000
Variable.3126       0.000000000
Variable.3128       0.058121429
Variable.3151       0.000000000
Variable.3164       0.000000000
Variable.3166       0.000000000
Variable.3181       0.018154762
Variable.3192       0.000000000
Variable.3208       0.000000000
Variable.3209       0.000000000
Variable.3216       0.008750000
Variable.3227       0.000000000
Variable.3241       0.027945984
Variable.3243       0.000000000
Variable.3259       0.000000000
Variable.3264       0.000000000
Variable.3288       0.015555556
Variable.3303       0.009677419
Variable.3304       0.000000000
Variable.3317       0.008888889
Variable.3334       0.000000000
Variable.3346       0.065522727
Variable.3347       0.000000000
Variable.3348       0.000000000
Variable.3365       0.000000000
Variable.3368       0.000000000
Variable.3370       0.000000000
Variable.3373       0.000000000
Variable.3382       0.000000000
Variable.3385       0.000000000
Variable.3403       0.034172709
Variable.3407       0.009655172
Variable.3415       0.000000000
Variable.3421       0.009777778
Variable.3430       0.000000000
Variable.3432       0.042864427
Variable.3440       0.000000000
Variable.3457       0.038148955
Variable.3460       0.023571429
Variable.3470       0.000000000
Variable.3479       0.000000000
Variable.3501       0.000000000
Variable.3510       0.062175301
Variable.3516       0.244902292
Variable.3542       0.124497706
Variable.3546       0.018307329
Variable.3557       0.000000000
Variable.3560       0.000000000
Variable.3574       0.007500000
Variable.3578       0.018116055
Variable.3582       0.000000000
Variable.3586       0.009565217
Variable.3593       0.008000000
Variable.3599       0.000000000
Variable.3600       0.000000000
Variable.3620       0.250770496
Variable.3629       0.225788794
Variable.3636       0.000000000
Variable.3638       0.000000000
Variable.3639       0.000000000
Variable.3643       0.000000000
Variable.3644       0.136446658
Variable.3646       0.000000000
Variable.3647       0.017777778
Variable.3662       0.000000000
Variable.3665       0.000000000
Variable.3679       0.000000000
Variable.3682       0.000000000
Variable.3683       0.000000000
Variable.3709       0.044826778
Variable.3717       0.000000000
Variable.3740       0.017833333
Variable.3754       0.030418587
Variable.3757       0.000000000
Variable.3764       0.000000000
Variable.3765       0.019305768
Variable.3779       0.000000000
Variable.3783       0.032980392
Variable.3785       0.008571429
Variable.3818       0.093232889
Variable.3820       0.000000000
Variable.3821       0.000000000
Variable.3826       0.000000000
Variable.3827       0.019245283
Variable.3834       0.012403101
Variable.3835       0.000000000
Variable.3861       0.000000000
Variable.3876       0.009722222
Variable.3878       0.000000000
Variable.3893       0.000000000
Variable.3896       0.019583333
Variable.3898       0.000000000
Variable.3900       0.000000000
Variable.3910       0.018918919
Variable.3912       0.000000000
Variable.3914       0.000000000
Variable.3918       0.000000000
Variable.3920       0.000000000
Variable.3929       0.007500000
Variable.3944       0.000000000
Variable.3945       0.017777778
Variable.3946       0.000000000
Variable.3954       0.000000000
Variable.3955       0.000000000
Variable.3962       0.000000000
Variable.3978       0.000000000
Variable.3979       0.000000000
Variable.3983       0.159381688
Variable.3984       0.000000000
Variable.3986       1.091302638
Variable.3989       0.000000000
Variable.3991       0.000000000
Variable.3992       0.000000000
Variable.4001       0.000000000
Variable.4007       0.064044325
Variable.4021       0.000000000
Variable.4022       0.000000000
Variable.4038       0.009761905
Variable.4039       0.000000000
Variable.4047       0.000000000
Variable.4058       0.000000000
Variable.4065       0.074020904
Variable.4068       0.031348148
Variable.4070       0.757313249
Variable.4084       0.000000000
Variable.4091       0.000000000
Variable.4094       0.000000000
Variable.4096       0.000000000
Variable.4104       0.000000000
Variable.4110       0.000000000
Variable.4113       0.000000000
Variable.4115       0.000000000
Variable.4117       0.007500000
Variable.4126       0.000000000
Variable.4129       0.014285714
Variable.4160       0.000000000
Variable.4169       0.049227273
Variable.4189       0.161107136
Variable.4192       2.063164614
Variable.4202       0.088746633
Variable.4229       0.101910777
Variable.4231       0.078898990
Variable.4241       0.000000000
Variable.4266       0.000000000
Variable.4272       0.000000000
Variable.4295       0.000000000
Variable.4303       0.000000000
Variable.4323       0.155429354
Variable.4348       0.000000000
Variable.4350       0.173330565
Variable.4353       0.000000000
Variable.4358       0.070533333
Variable.4367       0.025073260
Variable.4369       0.000000000
Variable.4374       0.000000000
Variable.4375       0.000000000
Variable.4381       0.052018519
Variable.4385       0.017500000
Variable.4395       0.000000000
Variable.4396       0.067298780
Variable.4400       0.070308787
Variable.4421       0.000000000
Variable.4423       0.000000000
Variable.4425       0.000000000
Variable.4441       0.000000000
Variable.4458       0.000000000
Variable.4463       0.000000000
Variable.4464       0.027233115
Variable.4479       0.058466117
Variable.4480       0.017633333
Variable.4484       0.000000000
Variable.4491       0.000000000
Variable.4496       0.000000000
Variable.4501       0.009827586
Variable.4514       0.000000000
Variable.4516       0.000000000
Variable.4519       0.028125000
Variable.4536       0.000000000
Variable.4544       0.000000000
Variable.4545       0.053286713
Variable.4547       0.000000000
Variable.4551       0.008333333
Variable.4571       0.009761905
Variable.4574       0.000000000
Variable.4590       0.000000000
Variable.4595       0.000000000
Variable.4602       0.000000000
Variable.4611       0.108842269
Variable.4614       0.000000000
Variable.4624       0.009526370
Variable.4625       0.000000000
Variable.4633       0.000000000
Variable.4637       0.009411765
Variable.4642       0.046515648
Variable.4661       0.000000000
Variable.4662       0.009814815
Variable.4669       0.009736842
Variable.4673       0.000000000
Variable.4678       1.044684553
Variable.4683       0.043392857
Variable.4692       0.000000000
Variable.4700       0.000000000
Variable.4708       0.000000000
Variable.4709       0.000000000
Variable.4716       0.000000000
Variable.4728       0.000000000
Variable.4729       0.008750000
Variable.4741       0.017595308
Variable.4747       0.000000000
Variable.4755       0.000000000
Variable.4762       0.076192313
Variable.4768       0.025000000
Variable.4770       0.009791667
Variable.4773       0.000000000
Variable.4787       0.281730417
Variable.4791       0.000000000
Variable.4797       0.042250000
Variable.4804       0.039039800
Variable.4806       0.009696970
Variable.4807       0.000000000
Variable.4810       0.000000000
Variable.4823       0.000000000
Variable.4840       0.000000000
Variable.4841       0.000000000
Variable.4845       0.028248248
Variable.4862       0.090045564
Variable.4873       0.000000000
Variable.4879       0.062504456
Variable.4886       0.000000000
Variable.4896       0.000000000
Variable.4897       0.000000000
Variable.4918       0.000000000
Variable.4933       0.000000000
Variable.4941       0.000000000
Variable.4946       0.037637209
Variable.4948       0.009736842
Variable.4956       0.019166667
Variable.4960       0.000000000
Variable.4961       0.000000000
Variable.4963       0.000000000
Variable.4967       0.116793830
Variable.4968       0.049597826
Variable.4979       0.000000000
Variable.4983       0.000000000
Variable.4984       0.000000000
Variable.4986       0.000000000
Variable.4999       0.000000000
Variable.5005       0.777580422
Variable.5011       0.009756098
Variable.5028       0.139357043
Variable.5041       0.000000000
Variable.5073       0.131101335
Variable.5080       0.000000000
Variable.5082       0.009782609
Variable.5083       0.000000000
Variable.5084       0.000000000
Variable.5089       0.066545783
Variable.5098       0.000000000
Variable.5108       0.015000000
Variable.5113       0.000000000
Variable.5123       0.000000000
Variable.5128       0.008750000
Variable.5135       0.036894118
Variable.5140       0.009756098
Variable.5146       0.000000000
Variable.5147       0.000000000
Variable.5184       0.123290712
Variable.5187       0.086811224
Variable.5193       0.087437500
Variable.5197       0.009333333
Variable.5203       0.009655172
Variable.5204       0.000000000
Variable.5211       0.008333333
Variable.5212       0.055847279
Variable.5223       0.211564144
Variable.5228       0.009230769
Variable.5232       0.000000000
Variable.5245       0.000000000
Variable.5259       0.000000000
Variable.5267       0.028800000
Variable.5276       0.000000000
Variable.5279       0.000000000
Variable.5281       0.000000000
Variable.5296       0.006666667
Variable.5300       0.018792614
Variable.5302       0.000000000
Variable.5303       0.034666667
Variable.5343       0.000000000
Variable.5345       0.000000000
Variable.5357       0.019259259
Variable.5380       0.000000000
Variable.5391       0.000000000
Variable.5393       0.000000000
Variable.5399       0.000000000
Variable.5419       0.000000000
Variable.5424       0.210961589
Variable.5427       0.053846154
Variable.5449       0.000000000
Variable.5451       0.041984127
Variable.5456       0.000000000
Variable.5458       0.000000000
Variable.5462       0.009791667
Variable.5469       0.019047619
Variable.5482       0.000000000
Variable.5486       0.000000000
Variable.5489       0.009743590
Variable.5496       0.000000000
Variable.5497       0.000000000
Variable.5503       0.000000000
Variable.5515       0.000000000
Variable.5522       0.000000000
Variable.5525       0.000000000
Variable.5527       0.000000000
Variable.5528       0.019111111
Variable.5529       0.000000000
Variable.5535       0.000000000
Variable.5547       0.000000000
Variable.5553       0.000000000
Variable.5554       0.000000000
Variable.5571       0.000000000
Variable.5578       0.000000000
Variable.5583       0.000000000
Variable.5586       0.017500000
Variable.5595       0.000000000
Variable.5603       0.056924242
Variable.5619       0.033546274
Variable.5621       0.061340659
Variable.5631       0.000000000
Variable.5638       0.000000000
Variable.5641       0.000000000
Variable.5670       0.000000000
Variable.5675       0.000000000
Variable.5679       0.050693050
Variable.5684       0.249108941
Variable.5700       0.000000000
Variable.5728       0.007500000
Variable.5744       0.000000000
Variable.5754       0.036201238
Variable.5758       0.000000000
Variable.5762       0.009655172
Variable.5770       0.000000000
Variable.5784       0.006666667
Variable.5796       0.000000000
Variable.5801       0.000000000
Variable.5802       0.000000000
Variable.5805       0.060444444
Variable.5811       0.074792344
Variable.5817       0.000000000
Variable.5844       0.028301887
Variable.5856       0.000000000
Variable.5858       0.090757146
Variable.5867       0.026354776
Variable.5868       0.000000000
Variable.5886       0.008000000
Variable.5896       0.000000000
Variable.5908       0.000000000
Variable.5913       0.000000000
Variable.5914       0.009821429
Variable.5922       0.000000000
Variable.5923       0.000000000
Variable.5935       0.043636364
Variable.5965       0.000000000
Variable.5984       0.040423977
Variable.5992       0.000000000
Variable.6004       0.000000000
Variable.6026       0.000000000
Variable.6034       0.000000000
Variable.6038       0.085203366
Variable.6049       0.000000000
Variable.6053       0.000000000
Variable.6058       0.025800000
Variable.6063       0.008750000
Variable.6072       0.000000000
Variable.6094       0.037211180
Variable.6097       0.000000000
Variable.6101       0.000000000
Variable.6126       0.045000000
Variable.6132       0.007500000
Variable.6134       0.000000000
Variable.6136       0.000000000
Variable.6140       0.217205302
Variable.6144       0.056278772
Variable.6145       0.020801887
Variable.6153       0.000000000
Variable.6157       0.000000000
Variable.6169       0.009090909
Variable.6171       0.009830508
Variable.6172       0.000000000
Variable.6180       0.000000000
Variable.6182       0.000000000
Variable.6190       0.000000000
Variable.6192       0.029333333
Variable.6199       0.009714286
Variable.6204       0.282965507
Variable.6215       0.000000000
Variable.6217       0.000000000
Variable.6218       0.019322034
Variable.6231       0.000000000
Variable.6243       0.000000000
Variable.6244       0.000000000
Variable.6247       0.046344828
Variable.6248       0.000000000
Variable.6251       0.000000000
Variable.6263       0.000000000
Variable.6266       0.000000000
Variable.6269       0.033875458
Variable.6280       0.064761905
Variable.6291       0.028269231
Variable.6307       0.031307692
Variable.6311       0.000000000
Variable.6319       0.000000000
Variable.6328       0.000000000
Variable.6336       0.293818208
Variable.6343       0.034047619
Variable.6344       0.000000000
Variable.6348       0.235293330
Variable.6352       0.067262258
Variable.6357       0.000000000
Variable.6358       0.106936564
Variable.6361       0.000000000
Variable.6367       0.009352657
Variable.6375       0.000000000
Variable.6380       0.000000000
Variable.6386       0.016363636
Variable.6396       0.009743590
Variable.6399       0.000000000
Variable.6404       0.000000000
Variable.6406       0.000000000
Variable.6412       0.000000000
Variable.6437       0.009307863
Variable.6442       0.241124667
Variable.6443       0.000000000
Variable.6444       0.000000000
Variable.6470       0.093911037
Variable.6481       1.704498168
Variable.6487       0.037463492
Variable.6502       0.047467043
Variable.6503       0.000000000
Variable.6508       0.000000000
Variable.6510       0.000000000
Variable.6511       0.000000000
Variable.6521       0.000000000
Variable.6532       0.000000000
Variable.6535       0.000000000
Variable.6562       0.000000000
Variable.6565       0.000000000
Variable.6576       0.000000000
Variable.6580       0.000000000
Variable.6591       0.000000000
Variable.6593       0.000000000
Variable.6594       0.000000000
Variable.6596       0.000000000
Variable.6601       0.000000000
Variable.6602       0.000000000
Variable.6607       0.000000000
Variable.6610       0.052175263
Variable.6631       0.000000000
Variable.6637       0.009677419
Variable.6639       0.094819562
Variable.6658       0.016363636
Variable.6659       0.000000000
Variable.6665       0.137289534
Variable.6680       0.015000000
Variable.6696       0.191128468
Variable.6697       0.000000000
Variable.6700       0.000000000
Variable.6709       0.023111111
Variable.6746       0.039756592
Variable.6748       0.058114379
Variable.6751       0.000000000
Variable.6752       0.009791667
Variable.6755       0.032142857
Variable.6756       0.009291521
Variable.6758       0.000000000
Variable.6775       0.000000000
Variable.6790       0.009722222
Variable.6800       0.080042443
Variable.6809       0.000000000
Variable.6813       0.000000000
Variable.6815       0.016363636
Variable.6817       0.000000000
Variable.6825       0.093078580
Variable.6842       0.000000000
Variable.6844       0.000000000
Variable.6877       0.000000000
Variable.6882       0.044572093
Variable.6883       0.000000000
Variable.6887       0.148357663
Variable.6888       0.000000000
Variable.6896       0.018232558
Variable.6906       0.000000000
Variable.6908       0.000000000
Variable.6913       0.027405074
Variable.6914       0.000000000
Variable.6917       0.000000000
Variable.6919       0.000000000
Variable.6924       0.019183673
Variable.6933       0.009043011
Variable.6934       0.054684362
Variable.6942       0.186856953
Variable.6944       0.000000000
Variable.6963       0.000000000
Variable.6966       0.000000000
Variable.6969       0.000000000
Variable.6974       0.000000000
Variable.6975       0.000000000
Variable.6980       0.000000000
Variable.6985       0.044009456
Variable.6993       0.000000000
Variable.7030       0.000000000
Variable.7038       0.119937325
Variable.7057       0.000000000
Variable.7074       0.043959330
Variable.7075       0.040562478
Variable.7094       0.000000000
Variable.7098       0.000000000
Variable.7112       0.018571429
Variable.7120       0.051558091
Variable.7136       0.000000000
Variable.7142       0.000000000
Variable.7143       0.000000000
Variable.7147       0.000000000
Variable.7174       0.000000000
Variable.7185       0.042000000
Variable.7188       0.009444444
Variable.7196       0.084783079
Variable.7199       0.000000000
Variable.7211       0.008888889
Variable.7217       0.009411765
Variable.7229       0.000000000
Variable.7232       0.170189780
Variable.7238       0.019635719
Variable.7242       0.009375000
Variable.7250       0.031766917
Variable.7263       0.000000000
Variable.7275       0.027806343
Variable.7276       0.000000000
Variable.7284       0.000000000
Variable.7305       0.077576029
Variable.7308       0.000000000
Variable.7322       0.000000000
Variable.7341       0.000000000
Variable.7344       0.008571429
Variable.7345       0.000000000
Variable.7358       0.000000000
Variable.7378       0.034851064
Variable.7386       0.082842407
Variable.7396       0.092533742
Variable.7401       0.000000000
Variable.7410       0.066047619
Variable.7414       0.000000000
Variable.7441       0.015000000
Variable.7446       0.000000000
Variable.7447       0.000000000
Variable.7462       0.000000000
Variable.7466       0.000000000
Variable.7481       0.018709677
Variable.7486       0.000000000
Variable.7494       0.049019608
Variable.7508       0.000000000
Variable.7515       0.008571429
Variable.7525       0.031578947
Variable.7532       0.000000000
Variable.7562       0.000000000
Variable.7564       0.417658252
Variable.7569       0.000000000
Variable.7579       0.120498575
Variable.7586       0.231886681
Variable.7594       0.000000000
Variable.7602       0.000000000
Variable.7628       0.000000000
Variable.7631       0.000000000
Variable.7648       0.000000000
Variable.7659       0.087500000
Variable.7719       0.075543850
Variable.7732       0.000000000
Variable.7734       0.186256102
Variable.7735       0.104386650
Variable.7767       0.114090146
Variable.7801       0.031510417
Variable.7803       0.094248797
Variable.7806       0.000000000
Variable.7819       0.033792240
Variable.7833       0.000000000
Variable.7852       0.000000000
Variable.7856       0.106736029
Variable.7859       0.018525641
Variable.7868       0.031803419
Variable.7884       0.052100653
Variable.7888       0.055030711
Variable.7889       0.000000000
Variable.7891       0.081225000
Variable.7908       0.374318644
Variable.7939       0.000000000
Variable.7954       0.000000000
Variable.7986       0.000000000
Variable.7995       0.061047409
Variable.7998       0.024000000
Variable.8001       0.009803922
Variable.8002       0.228688503
Variable.8014       0.000000000
Variable.8015       0.000000000
Variable.8017       0.054962224
Variable.8033       0.000000000
Variable.8036       0.000000000
Variable.8051       0.045902163
Variable.8057       0.000000000
Variable.8063       0.000000000
Variable.8071       0.074073225
Variable.8084       0.000000000
Variable.8088       0.105386501
Variable.8090       0.000000000
Variable.8114       0.000000000
Variable.8117       0.000000000
Variable.8121       0.000000000
Variable.8128       0.000000000
Variable.8131       0.018439376
Variable.8145       0.000000000
Variable.8160       0.017638889
Variable.8199       0.000000000
Variable.8200       0.061558442
Variable.8221       0.186966960
Variable.8243       0.000000000
Variable.8247       0.019130435
Variable.8263       0.008750000
Variable.8272       0.019200000
Variable.8281       0.000000000
Variable.8290       0.000000000
Variable.8291       0.101153932
Variable.8302       0.000000000
Variable.8322       0.000000000
Variable.8329       0.018750000
Variable.8331       0.027567568
Variable.8345       0.000000000
Variable.8348       0.000000000
Variable.8355       0.000000000
Variable.8356       0.000000000
Variable.8360       0.000000000
Variable.8367       0.000000000
Variable.8368       0.238090998
Variable.8388       0.084661101
Variable.8405       0.062400000
Variable.8422       0.000000000
Variable.8432       0.039928480
Variable.8436       0.000000000
Variable.8437       0.000000000
Variable.8446       0.023047619
Variable.8464       0.043959330
Variable.8495       0.000000000
Variable.8507       0.008000000
Variable.8508       0.174392232
Variable.8515       0.009053544
Variable.8519       0.048000000
Variable.8521       0.028593750
Variable.8523       0.000000000
Variable.8534       0.000000000
Variable.8548       0.009777778
Variable.8551       0.000000000
Variable.8572       0.015000000
Variable.8585       0.000000000
Variable.8590       0.017333333
Variable.8598       0.009705882
Variable.8639       0.000000000
Variable.8645       0.033179724
Variable.8653       0.100441824
Variable.8660       0.151967655
Variable.8685       0.000000000
Variable.8704       0.000000000
Variable.8709       0.027954545
Variable.8711       0.000000000
Variable.8717       0.000000000
Variable.8721       0.000000000
Variable.8722       0.000000000
Variable.8730       0.045370370
Variable.8732       0.000000000
Variable.8733       0.047085586
Variable.8736       0.000000000
Variable.8772       0.051586957
Variable.8795       0.009666667
Variable.8798       0.000000000
Variable.8810       0.000000000
Variable.8811       0.000000000
Variable.8816       0.000000000
Variable.8827       0.073563025
Variable.8850       0.000000000
Variable.8852       0.000000000
Variable.8858       0.000000000
Variable.8861       0.009787234
Variable.8872       0.000000000
Variable.8884       0.000000000
Variable.8896       0.000000000
Variable.8902       0.000000000
Variable.8903       0.000000000
Variable.8936       0.052419106
Variable.8942       0.000000000
Variable.8953       0.000000000
Variable.8966       0.009476817
Variable.8977       0.000000000
Variable.8994       0.000000000
Variable.9031       0.000000000
Variable.9043       0.000000000
Variable.9071       0.008888889
Variable.9074       0.000000000
Variable.9088       0.000000000
Variable.9092       0.026317889
Variable.9093       0.034533844
Variable.9129       0.076933137
Variable.9135       0.041988713
Variable.9156       0.061804651
Variable.9180       0.011713990
Variable.9183       0.049126794
Variable.9190       0.000000000
Variable.9198       0.000000000
Variable.9211       0.088084409
Variable.9238       0.897040578
Variable.9250       0.065154477
Variable.9262       0.051768010
Variable.9268       0.065275177
Variable.9273       0.000000000
Variable.9297       0.000000000
Variable.9327       0.000000000
Variable.9347       0.000000000
Variable.9356       0.087124940
Variable.9362       0.000000000
Variable.9393       0.000000000
Variable.9408       0.344668719
Variable.9417       0.019111111
Variable.9426       0.188135208
Variable.9432       0.116134938
Variable.9436       0.000000000
Variable.9447       0.000000000
Variable.9449       0.201146575
Variable.9451       0.000000000
Variable.9453       0.009782609
Variable.9463       0.000000000
Variable.9479       0.000000000
Variable.9483       0.036000000
Variable.9492       0.000000000
Variable.9493       0.028057985
Variable.9499       0.000000000
Variable.9513       0.000000000
Variable.9517       0.000000000
Variable.9534       0.000000000
Variable.9546       0.000000000
Variable.9549       0.000000000
Variable.9581       0.000000000
Variable.9587       0.000000000
Variable.9594       0.000000000
Variable.9603       0.000000000
Variable.9617       0.204919570
Variable.9636       0.000000000
Variable.9639       0.000000000
Variable.9642       0.049672474
Variable.9648       0.009230769
Variable.9651       0.000000000
Variable.9655       0.025454545
Variable.9660       0.000000000
Variable.9661       0.000000000
Variable.9689       0.000000000
Variable.9695       0.000000000
Variable.9708       0.000000000
Variable.9716       0.000000000
Variable.9722       0.009830508
Variable.9726       0.009090909
Variable.9741       0.000000000
Variable.9750       0.026812646
Variable.9769       0.018461538
Variable.9779       0.000000000
Variable.9780       0.000000000
Variable.9791       0.000000000
Variable.9819       0.000000000
Variable.9820       0.501980599
Variable.9821       0.000000000
Variable.9822       0.006666667
Variable.9833       0.085497326
Variable.9843       0.000000000
Variable.9850       0.568803710
Variable.9861       0.040518757
Variable.9870       0.009526370
Variable.9872       0.063750000
Variable.9873       0.024000000
Variable.9878       0.000000000
Variable.9879       0.000000000
Variable.9887       0.036627907
Variable.9910       0.046197360
Variable.9917       0.000000000
Variable.9950       0.000000000
Variable.9952       0.059090909
Variable.9954       0.023571429
Variable.9971       0.000000000
Variable.9985       0.039569767
Variable.9986       0.000000000
Variable.9999       0.046686321
Variable.7218       0.000000000
Variable.7209       0.000000000
Variable.2014       0.000000000
Variable.8591       0.009736842
Variable.1372       0.000000000
Variable.7876       0.000000000
Variable.749        0.009777778
Variable.314        0.000000000
Variable.3184       0.000000000
Variable.9498       0.000000000
Variable.2318       0.000000000
Variable.6711       0.035217391
Variable.9458       0.094372359
Variable.860        0.000000000
Variable.4676       0.000000000
Variable.3426       0.009642857
Variable.6561       0.000000000
Variable.5998       0.000000000
Variable.4076       0.000000000
Variable.3609       0.000000000
Variable.989        0.000000000
Variable.4460       0.000000000
Variable.3514       0.000000000
Variable.2848       0.008000000
Variable.3704       0.000000000
Variable.5494       0.000000000
Variable.4206       0.009807692
Variable.8510       0.000000000
Variable.7146       0.000000000
Variable.9277       0.000000000
Variable.3502       0.009090909
Variable.3144       0.000000000
Variable.1963       0.000000000
Variable.5075       0.000000000
Variable.3135       0.000000000
Variable.4264       0.025113636
Variable.2255       0.041515631
Variable.780        0.000000000
Variable.7056       0.015000000
Variable.510        0.000000000
Variable.9281       0.000000000
Variable.2032       0.017811321
Variable.8765       0.000000000
Variable.5646       0.019296537
Variable.2367       0.000000000
Variable.8318       0.000000000
Variable.4894       0.000000000
Variable.6410       0.000000000
Variable.2837       0.000000000
Variable.6064       0.019111111
Variable.9982       0.000000000
Variable.1346       0.040384615
Variable.1703       0.035416281
Variable.2617       0.028545752
Variable.7934       0.000000000
Variable.8241       0.000000000
Variable.4915       0.000000000
Variable.2454       0.000000000
Variable.7854       0.000000000
Variable.8372       0.050050616
Variable.2535       0.008000000
Variable.4159       0.009782609
Variable.5645       0.021818182
Variable.5798       0.000000000
Variable.1583       0.000000000
Variable.4681       0.000000000
Variable.5604       0.000000000
Variable.731        0.000000000
Variable.4398       0.016000000
Variable.1605       0.000000000
Variable.8945       0.028332730
Variable.8699       0.000000000
Variable.7195       0.074626136
Variable.9691       0.015000000
Variable.9434       0.000000000
Variable.8366       0.025195853
Variable.1662       0.000000000
Variable.5989       0.000000000
Variable.5148       0.080033333
Variable.7823       0.000000000
Variable.9805       0.016363636
Variable.8870       0.000000000
Variable.7573       0.000000000
Variable.2102       0.000000000
Variable.9646       0.008750000
Variable.1327       0.009677419
Variable.393        0.000000000
Variable.761        0.000000000
Variable.1380       0.000000000
Variable.920        0.045937500
Variable.2002       0.000000000
Variable.928        0.000000000
Variable.5479       0.000000000
Variable.9255       0.007500000
Variable.8824       0.000000000
Variable.1518       0.067520729
Variable.112        0.000000000
Variable.5327       0.000000000
Variable.5484       0.000000000
Variable.7607       0.000000000
Variable.5660       0.000000000
Variable.1843       0.000000000
Variable.7700       0.008888889
Variable.8068       0.019183673
Variable.7598       0.000000000
Variable.5143       0.049430233
Variable.543        0.000000000
Variable.5725       0.000000000
Variable.2516       0.000000000
Variable.6668       0.000000000
Variable.6828       0.000000000
Variable.7165       0.000000000
Variable.320        0.009090909
Variable.7493       0.000000000
Variable.7707       0.027857143
Variable.1607       0.000000000
Variable.4          0.000000000
Variable.1627       0.000000000
Variable.2127       0.000000000
Variable.4688       0.000000000
Variable.8504       0.000000000
Variable.2646       0.082858974
Variable.9747       0.000000000
Variable.7900       0.008750000
Variable.903        0.000000000
Variable.2831       0.000000000
Variable.2440       0.000000000
Variable.7477       0.000000000
Variable.9216       0.000000000
Variable.4233       0.000000000
Variable.8222       0.000000000
Variable.4280       0.000000000
Variable.169        0.000000000
Variable.8065       0.000000000
Variable.2244       0.000000000
Variable.2794       0.036601307
Variable.6691       0.012307692
Variable.8333       0.035041667
Variable.7621       0.045070352
Variable.7919       0.000000000
Variable.9537       0.008333333
Variable.645        0.000000000
Variable.1735       0.009411765
Variable.4878       0.009000000
Variable.8599       0.009777778
Variable.405        0.000000000
Variable.1606       0.000000000
Variable.222        0.000000000
Variable.9315       0.044833333
Variable.1453       0.139872693
Variable.9997       0.000000000
Variable.7037       0.000000000
Variable.8522       0.000000000
Variable.5952       0.000000000
Variable.7061       0.000000000
Variable.4214       0.000000000
Variable.1013       0.000000000
Variable.1364       0.025851064
Variable.8404       0.000000000
Variable.10         0.000000000
Variable.9981       0.000000000
Variable.2457       0.000000000
Variable.4751       0.027071078
Variable.9308       0.000000000
Variable.4737       0.000000000
Variable.5957       0.000000000
Variable.8111       0.030769231
Variable.368        0.000000000
Variable.6109       0.019518141
Variable.1561       0.000000000
Variable.7611       0.000000000
Variable.9924       0.000000000
Variable.6515       0.009814815
Variable.5381       0.009366327
Variable.8319       0.000000000
Variable.2269       0.000000000
Variable.2604       0.009782609
Variable.5076       0.000000000
Variable.1881       0.016363636
Variable.6161       0.000000000
Variable.4520       0.000000000
Variable.7328       0.000000000
Variable.8499       0.019148936
Variable.4882       0.000000000
Variable.5642       0.009827586
Variable.592        0.000000000
Variable.4535       0.000000000
Variable.8662       0.000000000
Variable.5931       0.000000000
Variable.7839       0.000000000
Variable.6968       0.000000000
Variable.7931       0.000000000
Variable.9481       0.008333333
Variable.2316       0.012482270
Variable.8681       0.074768648
Variable.4927       0.033152381
Variable.2273       0.000000000
Variable.8793       0.000000000
Variable.1296       0.000000000
Variable.6478       0.000000000
Variable.4629       0.025850340
Variable.5523       0.000000000
Variable.5918       0.000000000
Variable.9700       0.000000000
Variable.8549       0.000000000
Variable.8443       0.049839476
Variable.309        0.000000000
Variable.296        0.000000000
Variable.781        0.000000000
Variable.3611       0.000000000
Variable.7371       0.045267857
Variable.1946       0.031113636
Variable.2485       0.000000000
Variable.1333       0.000000000
Variable.9577       0.000000000
Variable.6653       0.017909357
Variable.8557       0.000000000
Variable.2494       0.000000000
Variable.7840       0.000000000
Variable.5644       0.008000000
Variable.7226       0.000000000
Variable.2762       0.035897436
Variable.7264       0.000000000
Variable.6099       0.000000000
Variable.5939       0.000000000
Variable.5537       0.034142512
Variable.4855       0.047024673
Variable.2443       0.000000000
Variable.8512       0.000000000
Variable.8817       0.000000000
Variable.796        0.000000000
Variable.5920       0.000000000
Variable.5383       0.043489890
Variable.1179       0.000000000
Variable.2346       0.000000000
Variable.111        0.000000000
Variable.4859       0.047516036
Variable.2070       0.000000000
Variable.7392       0.035400641
Variable.8047       0.000000000
Variable.7043       0.000000000
Variable.9162       0.009807692
Variable.2969       0.000000000
Variable.8940       0.000000000
Variable.3173       0.000000000
Variable.6806       0.000000000
Variable.3086       0.000000000
Variable.7665       0.000000000
Variable.55         0.000000000
Variable.9714       0.000000000
Variable.8361       0.033324583
Variable.6369       0.027844156
Variable.5121       0.000000000
Variable.9638       0.014666667
Variable.1324       0.000000000
Variable.1998       0.000000000
Variable.2937       0.000000000
Variable.5574       0.000000000
Variable.6304       0.000000000
Variable.9956       0.000000000
Variable.3242       0.099607703
Variable.7130       0.000000000
Variable.3916       0.000000000
Variable.5657       0.000000000
Variable.2703       0.009767442
Variable.9301       0.000000000
Variable.60         0.047923945
Variable.7316       0.024000000
Variable.9735       0.009800000
Variable.5587       0.007500000
Variable.4439       0.000000000
Variable.1665       0.000000000
Variable.4573       0.008750000
Variable.6080       0.000000000
Variable.7940       0.000000000
Variable.8165       0.000000000
Variable.4288       0.049777778
Variable.1940       0.000000000
Variable.3589       0.000000000
Variable.5928       0.000000000
Variable.3411       0.008888889
Variable.4604       0.032303107
Variable.4424       0.000000000
Variable.5331       0.000000000
Variable.6826       0.000000000
Variable.1319       0.009705882
Variable.3819       0.000000000
Variable.8403       0.000000000
Variable.8933       0.000000000
Variable.9505       0.000000000
Variable.9017       0.000000000
Variable.7089       0.000000000
Variable.1681       0.027567568
Variable.9274       0.000000000
Variable.6480       0.009756098
Variable.5055       0.000000000
Variable.620        0.000000000
Variable.2899       0.000000000
Variable.2830       0.008750000
Variable.2872       0.000000000
Variable.7485       0.009821429
Variable.151        0.000000000
Variable.9015       0.000000000
Variable.3023       0.096455395
Variable.7698       0.000000000
Variable.4543       0.000000000
Variable.9477       0.028571429
Variable.7645       0.000000000
Variable.8303       0.008888889
Variable.6636       0.018469231
Variable.888        0.015000000
Variable.6625       0.008000000
Variable.4617       0.000000000
Variable.241        0.038472727
Variable.2435       0.000000000
Variable.9682       0.000000000
Variable.5871       0.009642857
Variable.4826       0.000000000
Variable.273        0.000000000
Variable.3581       0.000000000
Variable.4660       0.000000000
Variable.6103       0.000000000
Variable.2028       0.070250896
Variable.666        0.000000000
Variable.1124       0.009750000
Variable.2194       0.027428571
Variable.3217       0.000000000
Variable.6501       0.000000000
Variable.7790       0.017853282
Variable.3148       0.000000000
Variable.4689       0.000000000
Variable.3724       0.000000000
Variable.3722       0.000000000
Variable.578        0.018777778
Variable.1301       0.000000000
Variable.2900       0.009666667
Variable.8752       0.000000000
Variable.7153       0.000000000
Variable.8822       0.000000000
Variable.1626       0.000000000
Variable.6721       0.039889277
Variable.7996       0.000000000
Variable.6979       0.194117219
Variable.9770       0.009523810
Variable.3397       0.025454545
Variable.3388       0.000000000
Variable.7350       0.045877913
Variable.4605       0.000000000
Variable.7186       0.000000000
Variable.1951       0.009787234
Variable.7765       0.030588235
Variable.1774       0.035300172
Variable.2453       0.049805280
Variable.958        0.009166667
Variable.2473       0.000000000
Variable.7786       0.000000000
Variable.3254       0.000000000
Variable.482        0.000000000
Variable.8310       0.000000000
Variable.9612       0.074638211
Variable.8426       0.000000000
Variable.3044       0.016666667
Variable.5572       0.000000000
Variable.2787       0.000000000
Variable.7187       0.000000000
Variable.4771       0.000000000
Variable.2331       0.000000000
Variable.2897       0.000000000
Variable.8785       0.000000000
Variable.3203       0.000000000
Variable.7009       0.000000000
Variable.7019       0.009729730
Variable.5421       0.009787234
Variable.1371       0.009392007
Variable.5892       0.000000000
Variable.8869       0.000000000
Variable.7994       0.033333333
Variable.4357       0.027127159
Variable.3475       0.000000000
Variable.1893       0.008571429
Variable.502        0.000000000
Variable.10000      0.000000000
Variable.2340       0.000000000
Variable.2451       0.000000000
Variable.9486       0.000000000
Variable.342        0.007500000
Variable.4498       0.000000000
Variable.6689       0.000000000
Variable.6704       0.000000000
Variable.669        0.052980549
Variable.799        0.000000000
Variable.6167       0.008333333
Variable.1751       0.000000000
Variable.295        0.000000000
Variable.1538       0.000000000
Variable.6425       0.000000000
Variable.9520       0.016923077
Variable.4884       0.000000000
Variable.102        0.034224599
Variable.9957       0.000000000
Variable.2632       0.000000000
Variable.6225       0.000000000
Variable.8518       0.012333333
Variable.9669       0.000000000
Variable.8332       0.000000000
Variable.6090       0.000000000
Variable.9834       0.169010222
Variable.7962       0.000000000
Variable.1522       0.000000000
Variable.5981       0.009000000
Variable.4694       0.000000000
Variable.7777       0.000000000
Variable.8992       0.008000000
Variable.1450       0.000000000
Variable.1439       0.000000000
Variable.6765       0.043094161
Variable.7495       0.000000000
Variable.7110       0.051303419
Variable.1244       0.000000000
Variable.728        0.008750000
Variable.7740       0.000000000
Variable.2098       0.000000000
Variable.8524       0.000000000
Variable.6085       0.008888889
Variable.8796       0.000000000
Variable.231        0.000000000
Variable.6530       0.000000000
Variable.3943       0.000000000
Variable.8773       0.008000000
Variable.1160       0.008000000
Variable.8723       0.000000000
Variable.285        0.000000000
Variable.969        0.000000000
Variable.1705       0.000000000
Variable.9528       0.035200000
Variable.50         0.000000000
Variable.2572       0.060149437
Variable.3824       0.000000000
Variable.6864       0.015555556
Variable.834        0.000000000
Variable.1657       0.000000000
Variable.7357       0.000000000
Variable.9593       0.000000000
Variable.2687       0.000000000
Variable.3341       0.000000000
Variable.7825       0.029333333
Variable.2530       0.000000000
Variable.5371       0.104704306
Variable.7156       0.000000000
Variable.411        0.000000000
Variable.6322       0.007500000
Variable.3566       0.000000000
Variable.4219       0.000000000
Variable.711        0.000000000
Variable.5453       0.033179724
Variable.9350       0.000000000
Variable.5878       0.108362225
Variable.1716       0.009772727
Variable.1630       0.000000000
Variable.2832       0.000000000
Variable.8173       0.009736842
Variable.7606       0.009787234
Variable.1939       0.000000000
Variable.7666       0.015416667
Variable.7526       0.009687500
Variable.9389       0.019298246
Variable.9784       0.000000000
Variable.7420       0.000000000
Variable.9590       0.000000000
Variable.2526       0.000000000
Variable.2056       0.000000000
Variable.2134       0.000000000
Variable.9756       0.000000000
Variable.9011       0.000000000
Variable.7499       0.000000000
Variable.5386       0.000000000
Variable.8883       0.000000000
Variable.703        0.018232558
Variable.811        0.000000000
Variable.7524       0.000000000
Variable.1336       0.000000000
Variable.6858       0.041580076
Variable.8692       0.018564815
Variable.963        0.000000000
Variable.28         0.000000000
Variable.262        0.000000000
Variable.9424       0.008333333
Variable.8169       0.000000000
Variable.3605       0.000000000
Variable.90         0.000000000
Variable.1245       0.111254475
Variable.9127       0.000000000
Variable.8423       0.000000000
Variable.6436       0.062261890
Variable.8906       0.016363636
Variable.7521       0.000000000
Variable.7871       0.000000000
Variable.2329       0.000000000
Variable.8152       0.000000000
Variable.9293       0.034375000
Variable.6411       0.000000000
Variable.2380       0.000000000
Variable.6469       0.000000000
Variable.9027       0.000000000
Variable.2275       0.000000000
Variable.5558       0.054244805
Variable.7148       0.000000000
Variable.1108       0.000000000
Variable.9311       0.000000000
Variable.5176       0.036905553
Variable.7853       0.000000000
Variable.54         0.000000000
Variable.8743       0.022500000
Variable.7529       0.036236802
Variable.6630       0.000000000
Variable.1541       0.000000000
Variable.7724       0.000000000
Variable.7846       0.009366327
Variable.133        0.000000000
Variable.3020       0.000000000
Variable.8213       0.014285714
Variable.8489       0.073686210
Variable.7235       0.017729730
Variable.7372       0.000000000
Variable.7855       0.000000000
Variable.9688       0.000000000
Variable.9512       0.000000000
Variable.2960       0.000000000
Variable.5838       0.000000000
Variable.8866       0.000000000
Variable.2067       0.000000000
Variable.8359       0.000000000
Variable.5017       0.017374677
Variable.7637       0.009756098
Variable.3305       0.000000000
Variable.4843       0.012592593
Variable.6224       0.000000000
Variable.509        0.046379599
Variable.394        0.071250157
Variable.6188       0.009818182
Variable.177        0.000000000
Variable.7615       0.000000000
Variable.1020       0.000000000
Variable.3837       0.000000000
Variable.9888       0.009756098
Variable.8398       0.000000000
Variable.1656       0.000000000
Variable.1456       0.000000000
Variable.9374       0.064394915
Variable.4704       0.000000000
Variable.1058       0.000000000
Variable.7892       0.008000000
Variable.7355       0.008888889
Variable.4712       0.000000000
Variable.8846       0.000000000
Variable.1436       0.000000000
Variable.2700       0.009767442
Variable.4937       0.000000000
Variable.360        0.009818182
Variable.6040       0.000000000
Variable.7673       0.000000000
Variable.2033       0.000000000
Variable.9680       0.000000000
Variable.8818       0.000000000
Variable.337        0.000000000
Variable.2481       0.000000000
Variable.91         0.000000000
Variable.8983       0.000000000
Variable.8305       0.000000000
Variable.9415       0.000000000
Variable.5734       0.000000000
Variable.3927       0.000000000
Variable.737        0.000000000
Variable.9042       0.000000000
Variable.6177       0.009843750
Variable.770        0.000000000
Variable.8304       0.000000000
Variable.2843       0.000000000
Variable.8275       0.000000000
Variable.3917       0.114049620
Variable.9991       0.000000000
Variable.7474       0.000000000
Variable.9407       0.000000000
Variable.9522       0.000000000
Variable.5134       0.000000000
Variable.2311       0.000000000
Variable.5324       0.000000000
Variable.7861       0.085514139
Variable.5056       0.009696970
Variable.839        0.000000000
Variable.181        0.000000000
Variable.3921       0.260118611
Variable.4388       0.000000000
Variable.470        0.018095238
Variable.3584       0.018061288
Variable.9578       0.000000000
Variable.7955       0.000000000
Variable.486        0.000000000
Variable.5031       0.025185315
Variable.8865       0.039019934
Variable.8855       0.000000000
Variable.4365       0.009629630
Variable.7349       0.000000000
Variable.8995       0.000000000
Variable.6507       0.000000000
Variable.2173       0.000000000
Variable.626        0.000000000
Variable.5584       0.000000000
Variable.9208       0.019772727
Variable.6862       0.000000000
Variable.8763       0.000000000
Variable.1874       0.000000000
Variable.4997       0.000000000
Variable.5480       0.000000000
Variable.9396       0.009818182
Variable.5814       0.000000000
Variable.4162       0.000000000
Variable.3200       0.000000000
Variable.376        0.034675785
Variable.7646       0.000000000
Variable.6388       0.000000000
Variable.2285       0.000000000
Variable.3262       0.000000000
Variable.2029       0.009795918
Variable.311        0.062192897
Variable.6275       0.035294118
Variable.7204       0.066247761
Variable.4234       0.000000000
Variable.1465       0.035675676
Variable.6486       0.000000000
Variable.6273       0.000000000
Variable.779        0.000000000
Variable.6915       0.000000000
Variable.2651       0.007500000
Variable.7654       0.008333333
Variable.9148       0.000000000
Variable.1999       0.017237517
Variable.4562       0.000000000
Variable.9402       0.017743590
Variable.736        0.000000000
Variable.7549       0.007500000
Variable.3968       0.000000000
Variable.6374       0.008750000
Variable.5676       0.000000000
Variable.9893       0.000000000
Variable.4368       0.000000000
Variable.7453       0.000000000
Variable.554        0.007500000
Variable.2393       0.009642857
Variable.9413       0.000000000
Variable.3913       0.091369986
Variable.6814       0.022083333
Variable.7688       0.000000000
Variable.1629       0.000000000
Variable.7558       0.009814815
Variable.7248       0.000000000
Variable.371        0.000000000
Variable.2909       0.000000000
Variable.8735       0.046234349
Variable.4939       0.000000000
Variable.5854       0.000000000
Variable.9326       0.000000000
Variable.1631       0.000000000
Variable.657        0.041454545
Variable.6514       0.000000000
Variable.742        0.000000000
Variable.3417       0.000000000
Variable.1221       0.022500000
Variable.544        0.000000000
Variable.999        0.000000000
Variable.8209       0.000000000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">varImpPlot</span>(Model.bagging, <span class="at">main=</span><span class="st">"predicting class"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cancerwork_tree_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>According to the bagging forest, Variable.2640 is the most important factor, followed by Variable.4192 and Variable.6481, Variable.132 and Variable.1193, Variable.6442 and Variable.1235 are relatively unimportant.</p>
</section>
<section id="roc-and-auc-1" class="level4">
<h4 class="anchored" data-anchor-id="roc-and-auc-1">ROC and AUC:</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ROCR)</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>pred.prob <span class="ot">&lt;-</span> <span class="fu">predict</span>(Model.bagging,<span class="at">newdata =</span> testdata2,<span class="at">type =</span> <span class="st">"prob"</span>)[,<span class="dv">2</span>]</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>true_labels <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">as.character</span>(testdata2<span class="sc">$</span>Class))</span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>true_labels[true_labels <span class="sc">==</span> <span class="sc">-</span><span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>score2 <span class="ot">&lt;-</span> <span class="fu">prediction</span>(pred.prob,true_labels)</span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a>perf2 <span class="ot">&lt;-</span> <span class="fu">performance</span>(score2,<span class="st">"tpr"</span>,<span class="st">"fpr"</span>)</span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a>auc2 <span class="ot">&lt;-</span> <span class="fu">performance</span>(score2,<span class="st">"auc"</span>)</span>
<span id="cb61-9"><a href="#cb61-9" aria-hidden="true" tabindex="-1"></a>perfd2 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x=</span>perf2<span class="sc">@</span>x.values[<span class="dv">1</span>][[<span class="dv">1</span>]],<span class="at">y=</span>perf2<span class="sc">@</span>y.values[<span class="dv">1</span>][[<span class="dv">1</span>]])</span>
<span id="cb61-10"><a href="#cb61-10" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(perfd2,<span class="fu">aes</span>(<span class="at">x=</span>x,<span class="at">y=</span>y))<span class="sc">+</span><span class="fu">geom_line</span>()<span class="sc">+</span></span>
<span id="cb61-11"><a href="#cb61-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"False positive rate"</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">"True positive rate"</span>) <span class="sc">+</span></span>
<span id="cb61-12"><a href="#cb61-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="fu">paste</span>(<span class="st">"Area under the curve:"</span>, <span class="fu">round</span>(auc2<span class="sc">@</span>y.values[[<span class="dv">1</span>]], <span class="dv">3</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cancerwork_tree_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The ROC curve show the classification performance. A higher AUC(close to 1 ) indicates a better-performing model. The AUC of bagging forest is 0.921, which is greater than 0.5 and close to 1, show the classification effect is excellent.</p>
<p>Prediction:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>bagg.pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(Model.bagging,<span class="at">newdata =</span> testdata2[,<span class="sc">-</span><span class="fu">ncol</span>(testdata2)],<span class="at">type=</span><span class="st">"class"</span>)</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>test.table.bagg <span class="ot">&lt;-</span> <span class="fu">table</span>(testdata2<span class="sc">$</span>Class,bagg.pred)</span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(test.table.bagg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   bagg.pred
     0  1
  0 49  7
  1 14 30</code></pre>
</div>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>accuracy <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">diag</span>(test.table.bagg))<span class="sc">/</span><span class="fu">sum</span>(test.table.bagg)</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(accuracy)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.79</code></pre>
</div>
</div>
<p>After the predict of the test set, obtained the Confusion Matrix and the Accuracy. The Accuracy of test set is 0.79, which is good. The bagging forest model has good classification ability.</p>
</section>
</section>
<section id="random-forests" class="level3">
<h3 class="anchored" data-anchor-id="random-forests">Random Forests</h3>
<p>Description: Random forests improve upon bagging by decorrelating the individual trees. By forcibly excluding a random subset of variables, the correlation between any pair of trees is reduced. Therefore the average predictions will be more reliable.</p>
<p>Reason: Reduce the overfitting risk of a single tree, avoid strong feature influence ,improve the stability and performance of the model, make the average predictions will be more reliable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="co">#random forest</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2023</span>)</span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>Model.random <span class="ot">&lt;-</span> <span class="fu">randomForest</span>(Class<span class="sc">~</span>.,<span class="at">data=</span>traindata2,<span class="at">ntree=</span><span class="dv">500</span>)</span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a>Model.random</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
 randomForest(formula = Class ~ ., data = traindata2, ntree = 500) 
               Type of random forest: classification
                     Number of trees: 500
No. of variables tried at each split: 42

        OOB estimate of  error rate: 16%
Confusion matrix:
   0  1 class.error
0 49  7   0.1250000
1  9 35   0.2045455</code></pre>
</div>
</div>
<p>Start with randomForest() function and the data set is full train data, because random forests have seletion. Set the ntree= 500, check the out-of-bag estimate of error rate.</p>
<section id="obb" class="level4">
<h4 class="anchored" data-anchor-id="obb">OBB:</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Model.random<span class="sc">$</span>err.rate[,<span class="dv">1</span>],<span class="at">type =</span> <span class="st">"l"</span>,</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Number of trees"</span>,<span class="at">ylab=</span><span class="st">"OOB Error"</span>,<span class="at">main=</span><span class="st">"OBB Error vs. Number of Trees"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cancerwork_tree_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>According to the graph, in the range of (400,500), the OOB error starts to stabilize after decreasing. So we don’t change the ntree.</p>
</section>
<section id="variable-importance-2" class="level4">
<h4 class="anchored" data-anchor-id="variable-importance-2">Variable Importance:</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">importance</span>(Model.random)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               MeanDecreaseGini
Variable.6         0.0148209202
Variable.7         0.0789350618
Variable.15        0.0238842334
Variable.16        0.0186851228
Variable.25        0.0147272727
Variable.29        0.0505737053
Variable.40        0.0247894325
Variable.43        0.0217694496
Variable.45        0.0110002527
Variable.69        0.0233769369
Variable.83        0.0067692308
Variable.103       0.0098823529
Variable.107       0.0000000000
Variable.108       0.0000000000
Variable.109       0.0249821467
Variable.113       0.0115238095
Variable.118       0.0064000000
Variable.132       0.1443155474
Variable.143       0.0000000000
Variable.153       0.0402594987
Variable.168       0.0585792014
Variable.172       0.0393417507
Variable.193       0.0035555556
Variable.202       0.0062000000
Variable.211       0.0309412468
Variable.214       0.0000000000
Variable.215       0.0000000000
Variable.218       0.0687395422
Variable.258       0.0099269841
Variable.261       0.0000000000
Variable.263       0.1097826445
Variable.281       0.1008739208
Variable.294       0.0915259150
Variable.301       0.0000000000
Variable.312       0.1547142317
Variable.325       0.0165142857
Variable.327       0.1120060485
Variable.331       0.0351581791
Variable.332       0.0359357251
Variable.345       0.0088333333
Variable.346       0.0036870555
Variable.363       0.0000000000
Variable.370       0.0760632080
Variable.381       0.0000000000
Variable.382       0.0415089753
Variable.392       0.0142222222
Variable.398       0.0481949162
Variable.400       0.0000000000
Variable.403       0.0252477360
Variable.409       0.0289011672
Variable.414       0.1169828139
Variable.426       0.0084524674
Variable.430       0.1084214055
Variable.433       0.0000000000
Variable.456       0.0210825127
Variable.457       0.0175747380
Variable.471       0.2710729721
Variable.474       0.0103030303
Variable.484       0.0818776833
Variable.496       0.0000000000
Variable.498       0.0257085671
Variable.501       0.0000000000
Variable.507       0.0000000000
Variable.508       0.0169553414
Variable.521       0.0149019608
Variable.540       0.0124444444
Variable.549       0.0390378632
Variable.577       0.0980713518
Variable.600       0.0109597070
Variable.613       0.0472305227
Variable.636       0.0096000000
Variable.640       0.0170843675
Variable.643       0.0272152064
Variable.659       0.0300173768
Variable.661       0.0140122535
Variable.664       0.0000000000
Variable.686       0.0445272055
Variable.701       0.0469476857
Variable.717       0.0542228212
Variable.732       0.0520993136
Variable.746       0.0081403509
Variable.768       0.0342035450
Variable.775       0.0038400000
Variable.806       0.0151219512
Variable.827       0.0000000000
Variable.830       0.0520257441
Variable.835       0.0320137609
Variable.840       0.0216566384
Variable.844       0.0000000000
Variable.847       0.0345385149
Variable.848       0.0187595819
Variable.857       0.0115324675
Variable.858       0.1076268054
Variable.868       0.0174355407
Variable.887       0.0000000000
Variable.908       0.0312882744
Variable.911       0.0050129870
Variable.913       0.0897275460
Variable.919       0.0542207792
Variable.926       0.0222325889
Variable.934       0.0062978208
Variable.941       0.0000000000
Variable.949       0.0384309565
Variable.951       0.0066500000
Variable.954       0.0135777751
Variable.982       0.0443113230
Variable.995       0.0925085638
Variable.1001      0.0226412281
Variable.1016      0.0297490312
Variable.1022      0.0839628787
Variable.1023      0.0000000000
Variable.1038      0.0093122172
Variable.1043      0.0095000000
Variable.1057      0.0101587302
Variable.1059      0.0317565324
Variable.1067      0.0060000000
Variable.1070      0.0000000000
Variable.1085      0.0432528304
Variable.1093      0.0111130435
Variable.1096      0.0246281811
Variable.1105      0.0104631396
Variable.1112      0.0149629630
Variable.1127      0.0240752974
Variable.1131      0.0000000000
Variable.1132      0.0194687747
Variable.1135      0.0155245894
Variable.1137      0.0147134823
Variable.1142      0.0000000000
Variable.1146      0.0345768831
Variable.1148      0.0686639983
Variable.1149      0.0035000000
Variable.1154      0.0000000000
Variable.1169      0.0216759593
Variable.1172      0.0120000000
Variable.1181      0.0324615731
Variable.1193      0.1257656065
Variable.1194      0.0078156863
Variable.1204      0.0299212343
Variable.1223      0.0020000000
Variable.1231      0.0000000000
Variable.1235      0.1017504957
Variable.1236      0.0000000000
Variable.1239      0.0262112878
Variable.1242      0.0030000000
Variable.1251      0.0175930736
Variable.1257      0.0198640110
Variable.1260      0.0378993129
Variable.1262      0.0000000000
Variable.1263      0.0000000000
Variable.1271      0.0039230769
Variable.1285      0.0234200807
Variable.1288      0.0129754386
Variable.1297      0.0644188232
Variable.1310      0.0599301116
Variable.1311      0.0184620047
Variable.1342      0.0158469678
Variable.1367      0.0037333333
Variable.1374      0.0066666667
Variable.1379      0.0578983378
Variable.1390      0.0000000000
Variable.1391      0.0252992481
Variable.1395      0.0219044342
Variable.1400      0.1075248994
Variable.1402      0.0000000000
Variable.1407      0.0000000000
Variable.1409      0.0134836320
Variable.1411      0.1101475014
Variable.1413      0.0128205128
Variable.1419      0.0311082986
Variable.1438      0.0274238815
Variable.1449      0.0532559043
Variable.1454      0.0330663864
Variable.1455      0.1296838825
Variable.1462      0.0697044136
Variable.1463      0.0156444444
Variable.1464      0.0343997735
Variable.1466      0.0332362088
Variable.1494      0.0000000000
Variable.1496      0.0069723145
Variable.1499      0.0263563791
Variable.1500      0.0060000000
Variable.1508      0.0563065584
Variable.1510      0.0244661019
Variable.1512      0.0461916628
Variable.1513      0.1201677751
Variable.1516      0.0035000000
Variable.1530      0.0086302171
Variable.1531      0.0877608715
Variable.1556      0.0134509804
Variable.1567      0.0030000000
Variable.1591      0.0879389243
Variable.1597      0.0298171429
Variable.1603      0.0443252763
Variable.1616      0.0043650794
Variable.1619      0.0197490457
Variable.1634      0.0039200000
Variable.1649      0.0060000000
Variable.1654      0.0057142857
Variable.1660      0.0176646900
Variable.1661      0.0204000000
Variable.1671      0.1065628319
Variable.1673      0.0000000000
Variable.1674      0.0601765259
Variable.1675      0.0131367521
Variable.1680      0.0153653817
Variable.1682      0.0086298003
Variable.1702      0.0000000000
Variable.1711      0.0134095238
Variable.1721      0.0060000000
Variable.1730      0.0165097436
Variable.1736      0.0325093816
Variable.1746      0.0000000000
Variable.1768      0.0034285714
Variable.1779      0.0300616178
Variable.1805      0.0134940541
Variable.1823      0.0107405342
Variable.1824      0.0138666667
Variable.1830      0.0000000000
Variable.1832      0.0151655917
Variable.1835      0.0100540117
Variable.1849      0.0604442327
Variable.1850      0.0416479152
Variable.1870      0.0130347850
Variable.1915      0.0163845021
Variable.1919      0.0104142857
Variable.1925      0.0432401512
Variable.1936      0.0956439301
Variable.1937      0.0235362839
Variable.1967      0.0154133333
Variable.1990      0.0105000000
Variable.1992      0.0030000000
Variable.2000      0.0847083936
Variable.2005      0.0000000000
Variable.2020      0.0188786450
Variable.2022      0.2175007058
Variable.2026      0.0000000000
Variable.2040      0.0303872890
Variable.2045      0.0229545734
Variable.2057      0.0529131968
Variable.2061      0.0943374795
Variable.2071      0.0166284017
Variable.2072      0.0192599681
Variable.2077      0.0473654088
Variable.2087      0.0191181614
Variable.2097      0.0470497579
Variable.2099      0.0077765446
Variable.2101      0.0900643959
Variable.2106      0.0296204910
Variable.2107      0.0352798762
Variable.2121      0.0375988238
Variable.2126      0.0299930060
Variable.2128      0.0396696248
Variable.2146      0.0423469909
Variable.2155      0.0822730174
Variable.2174      0.0072380952
Variable.2180      0.0493395701
Variable.2190      0.0874561983
Variable.2199      0.0032000000
Variable.2216      0.0384470117
Variable.2234      0.0935570493
Variable.2243      0.0272201957
Variable.2247      0.0104710145
Variable.2280      0.0209592593
Variable.2283      0.0136821256
Variable.2284      0.0000000000
Variable.2294      0.0448530962
Variable.2297      0.0000000000
Variable.2309      0.2098722098
Variable.2325      0.0038620690
Variable.2334      0.0000000000
Variable.2348      0.0322065449
Variable.2351      0.0140921379
Variable.2357      0.0555518811
Variable.2361      0.0068571429
Variable.2364      0.0102357724
Variable.2365      0.0397973366
Variable.2373      0.0411920560
Variable.2432      0.0185085470
Variable.2442      0.0209773335
Variable.2503      0.0487064960
Variable.2506      0.0073025641
Variable.2510      0.0893028014
Variable.2517      0.0996726160
Variable.2519      0.0000000000
Variable.2525      0.0607563282
Variable.2528      0.0201269841
Variable.2534      0.0086666667
Variable.2539      0.0142364532
Variable.2542      0.0037025641
Variable.2556      0.1333737243
Variable.2557      0.0035555556
Variable.2562      0.0000000000
Variable.2575      0.0038571429
Variable.2577      0.0000000000
Variable.2583      0.0710864101
Variable.2591      0.0036000000
Variable.2605      0.0168285205
Variable.2608      0.0583765580
Variable.2629      0.1118180696
Variable.2640      0.4235462560
Variable.2644      0.0181883830
Variable.2648      0.0218290366
Variable.2652      0.0313173542
Variable.2655      0.0000000000
Variable.2658      0.0253026528
Variable.2683      0.0000000000
Variable.2684      0.0170136919
Variable.2688      0.0354698006
Variable.2690      0.0000000000
Variable.2694      0.0000000000
Variable.2706      0.0038857143
Variable.2710      0.0260270544
Variable.2737      0.0166102786
Variable.2744      0.0219060839
Variable.2748      0.0210285714
Variable.2752      0.0073369565
Variable.2753      0.0185893980
Variable.2763      0.0124444444
Variable.2777      0.0521297321
Variable.2789      0.0775015221
Variable.2798      0.0340725265
Variable.2801      0.1076756284
Variable.2807      0.0172442688
Variable.2809      0.0104784053
Variable.2816      0.0380291646
Variable.2817      0.0182467105
Variable.2818      0.1255186406
Variable.2842      0.0030000000
Variable.2854      0.0219050283
Variable.2862      0.0155905968
Variable.2866      0.0862433091
Variable.2878      0.0392746155
Variable.2895      0.0145612903
Variable.2902      0.0571226617
Variable.2905      0.0745906139
Variable.2907      0.0146416422
Variable.2914      0.0714033959
Variable.2928      0.0301355825
Variable.2929      0.0030000000
Variable.2933      0.0117333333
Variable.2945      0.0035446154
Variable.2952      0.0176400000
Variable.2956      0.0507484165
Variable.2957      0.0439860508
Variable.2958      0.0000000000
Variable.2968      0.0381017690
Variable.2980      0.0179638838
Variable.2989      0.0290448985
Variable.3010      0.0064473684
Variable.3012      0.0037647059
Variable.3017      0.0149776579
Variable.3026      0.0046376812
Variable.3036      0.0744273194
Variable.3073      0.0009024390
Variable.3075      0.0108740942
Variable.3083      0.0361234208
Variable.3091      0.0297330917
Variable.3100      0.0177014805
Variable.3111      0.0200178571
Variable.3115      0.0828450636
Variable.3125      0.0000000000
Variable.3126      0.0077571429
Variable.3128      0.0980823513
Variable.3151      0.0317242333
Variable.3164      0.0100000000
Variable.3166      0.0137622005
Variable.3181      0.0000000000
Variable.3192      0.0255789474
Variable.3208      0.0000000000
Variable.3209      0.0000000000
Variable.3216      0.0413502652
Variable.3227      0.0267061776
Variable.3241      0.0734219968
Variable.3243      0.1188058844
Variable.3259      0.0249364706
Variable.3264      0.0243219048
Variable.3288      0.0203547301
Variable.3303      0.1049064839
Variable.3304      0.0000000000
Variable.3317      0.0196099773
Variable.3334      0.0290009023
Variable.3346      0.0531051955
Variable.3347      0.0449474099
Variable.3348      0.0000000000
Variable.3365      0.0848302357
Variable.3368      0.0173480858
Variable.3370      0.0044390244
Variable.3373      0.0069766407
Variable.3382      0.0097121212
Variable.3385      0.0263818441
Variable.3403      0.0984168674
Variable.3407      0.0026666667
Variable.3415      0.0244833145
Variable.3421      0.0000000000
Variable.3430      0.0045002506
Variable.3432      0.0072727273
Variable.3440      0.0364429394
Variable.3457      0.0109214703
Variable.3460      0.0000000000
Variable.3470      0.0198909091
Variable.3479      0.0296154917
Variable.3501      0.0066442688
Variable.3510      0.0039200000
Variable.3516      0.0676957512
Variable.3542      0.0406912142
Variable.3546      0.0171911330
Variable.3557      0.0516124868
Variable.3560      0.0239021053
Variable.3574      0.0045002506
Variable.3578      0.0685052982
Variable.3582      0.0088888889
Variable.3586      0.0096428571
Variable.3593      0.0210179405
Variable.3599      0.0256908396
Variable.3600      0.0354321054
Variable.3620      0.0575396594
Variable.3629      0.1530967229
Variable.3636      0.0104210526
Variable.3638      0.0366352803
Variable.3639      0.0000000000
Variable.3643      0.0035555556
Variable.3644      0.0108539750
Variable.3646      0.0188877980
Variable.3647      0.0036698413
Variable.3662      0.0544684489
Variable.3665      0.0303820639
Variable.3679      0.0026666667
Variable.3682      0.0000000000
Variable.3683      0.0000000000
Variable.3709      0.0576825747
Variable.3717      0.0257925810
Variable.3740      0.0000000000
Variable.3754      0.0634216479
Variable.3757      0.0829001931
Variable.3764      0.0350169976
Variable.3765      0.0394622222
Variable.3779      0.0091671088
Variable.3783      0.1173763331
Variable.3785      0.0037870130
Variable.3818      0.0193594771
Variable.3820      0.0553878036
Variable.3821      0.0048000000
Variable.3826      0.0082139037
Variable.3827      0.0372071910
Variable.3834      0.0487505804
Variable.3835      0.0000000000
Variable.3861      0.0000000000
Variable.3876      0.0096203987
Variable.3878      0.0000000000
Variable.3893      0.0067500000
Variable.3896      0.0064192393
Variable.3898      0.0000000000
Variable.3900      0.0373728449
Variable.3910      0.0941481872
Variable.3912      0.0106728205
Variable.3914      0.0216732293
Variable.3918      0.0121977324
Variable.3920      0.0201018294
Variable.3929      0.0185681001
Variable.3944      0.0144821716
Variable.3945      0.0000000000
Variable.3946      0.0577092433
Variable.3954      0.0000000000
Variable.3955      0.0026666667
Variable.3962      0.0180266962
Variable.3978      0.0246622202
Variable.3979      0.0298168184
Variable.3983      0.0220952381
Variable.3984      0.0179581477
Variable.3986      0.3693444455
Variable.3989      0.0259859459
Variable.3991      0.0171438561
Variable.3992      0.0000000000
Variable.4001      0.0000000000
Variable.4007      0.1546038426
Variable.4021      0.0277829803
Variable.4022      0.0387397185
Variable.4038      0.1021934301
Variable.4039      0.0133948052
Variable.4047      0.0442661041
Variable.4058      0.0000000000
Variable.4065      0.0229966534
Variable.4068      0.0138333333
Variable.4070      0.1153522114
Variable.4084      0.0411478691
Variable.4091      0.0000000000
Variable.4094      0.0447801603
Variable.4096      0.0057142857
Variable.4104      0.0216804233
Variable.4110      0.0114603175
Variable.4113      0.0387383433
Variable.4115      0.0419344806
Variable.4117      0.0000000000
Variable.4126      0.0130722154
Variable.4129      0.0038461538
Variable.4160      0.0150683439
Variable.4169      0.0450341944
Variable.4189      0.1147210634
Variable.4192      0.3806871172
Variable.4202      0.0726490139
Variable.4229      0.0594751511
Variable.4231      0.0208315995
Variable.4241      0.0921460723
Variable.4266      0.0038974359
Variable.4272      0.0374310134
Variable.4295      0.0288641191
Variable.4303      0.0266334235
Variable.4323      0.0456383468
Variable.4348      0.0334328507
Variable.4350      0.0831659509
Variable.4353      0.0519843555
Variable.4358      0.1137676336
Variable.4367      0.0249443571
Variable.4369      0.0000000000
Variable.4374      0.0379557302
Variable.4375      0.0000000000
Variable.4381      0.0521521595
Variable.4385      0.0068571429
Variable.4395      0.0486941654
Variable.4396      0.0673219641
Variable.4400      0.0781781691
Variable.4421      0.0255522845
Variable.4423      0.0075718251
Variable.4425      0.0111171930
Variable.4441      0.0370184127
Variable.4458      0.0109285714
Variable.4463      0.0548101765
Variable.4464      0.0519359150
Variable.4479      0.0221180579
Variable.4480      0.0323096803
Variable.4484      0.0039024390
Variable.4491      0.0499733375
Variable.4496      0.0516661339
Variable.4501      0.0265091480
Variable.4514      0.0000000000
Variable.4516      0.0320592884
Variable.4519      0.0205574796
Variable.4536      0.0038518519
Variable.4544      0.0000000000
Variable.4545      0.0755495622
Variable.4547      0.0230759098
Variable.4551      0.0000000000
Variable.4571      0.0335835343
Variable.4574      0.0200846753
Variable.4590      0.0073133641
Variable.4595      0.0037097561
Variable.4602      0.0064374057
Variable.4611      0.0353438257
Variable.4614      0.0189736017
Variable.4624      0.0158636547
Variable.4625      0.0609755484
Variable.4633      0.0536560895
Variable.4637      0.0038666667
Variable.4642      0.0552767314
Variable.4661      0.0182014066
Variable.4662      0.0253375064
Variable.4669      0.1005852874
Variable.4673      0.0127247059
Variable.4678      0.1721580124
Variable.4683      0.0256093506
Variable.4692      0.0109097744
Variable.4700      0.0321743140
Variable.4708      0.0102698413
Variable.4709      0.0196120401
Variable.4716      0.0075049933
Variable.4728      0.0037333333
Variable.4729      0.0525964841
Variable.4741      0.0000000000
Variable.4747      0.0000000000
Variable.4755      0.0821816227
Variable.4762      0.0248263720
Variable.4768      0.0245935921
Variable.4770      0.0039272727
Variable.4773      0.0113694118
Variable.4787      0.0930124891
Variable.4791      0.0074666667
Variable.4797      0.0000000000
Variable.4804      0.0036045977
Variable.4806      0.0246544821
Variable.4807      0.0000000000
Variable.4810      0.0440839724
Variable.4823      0.0105979735
Variable.4840      0.0000000000
Variable.4841      0.0156385281
Variable.4845      0.0038823529
Variable.4862      0.0353442274
Variable.4873      0.0584049563
Variable.4879      0.1276405353
Variable.4886      0.0057142857
Variable.4896      0.0140333690
Variable.4897      0.0000000000
Variable.4918      0.0292231820
Variable.4933      0.0000000000
Variable.4941      0.0000000000
Variable.4946      0.0180150830
Variable.4948      0.0084747899
Variable.4956      0.0282939806
Variable.4960      0.0860592280
Variable.4961      0.0110508788
Variable.4963      0.0000000000
Variable.4967      0.0711992194
Variable.4968      0.0119095238
Variable.4979      0.0091844156
Variable.4983      0.0088896104
Variable.4984      0.0000000000
Variable.4986      0.0055433404
Variable.4999      0.0130932897
Variable.5005      0.1897918718
Variable.5011      0.0279242347
Variable.5028      0.0106713455
Variable.5041      0.0000000000
Variable.5073      0.0485613373
Variable.5080      0.0336876370
Variable.5082      0.0000000000
Variable.5083      0.0332050422
Variable.5084      0.0000000000
Variable.5089      0.0249719672
Variable.5098      0.0265568506
Variable.5108      0.0540926027
Variable.5113      0.0000000000
Variable.5123      0.0097500000
Variable.5128      0.0429659685
Variable.5135      0.0000000000
Variable.5140      0.0033333333
Variable.5146      0.0080842105
Variable.5147      0.0297335866
Variable.5184      0.0526486210
Variable.5187      0.0772005622
Variable.5193      0.0493691234
Variable.5197      0.0382695657
Variable.5203      0.0640488828
Variable.5204      0.0000000000
Variable.5211      0.0000000000
Variable.5212      0.0000000000
Variable.5223      0.0701681690
Variable.5228      0.0026666667
Variable.5232      0.0678071964
Variable.5245      0.0170066378
Variable.5259      0.0360681361
Variable.5267      0.0218870968
Variable.5276      0.0175109232
Variable.5279      0.0274842134
Variable.5281      0.0000000000
Variable.5296      0.0308564052
Variable.5300      0.0000000000
Variable.5302      0.0064000000
Variable.5303      0.0501933012
Variable.5343      0.0206185415
Variable.5345      0.0101080921
Variable.5357      0.0000000000
Variable.5380      0.0790917302
Variable.5391      0.0222956643
Variable.5393      0.0772615445
Variable.5399      0.0231575092
Variable.5419      0.0034260250
Variable.5424      0.0150826507
Variable.5427      0.0091115301
Variable.5449      0.0036363636
Variable.5451      0.0370338091
Variable.5456      0.0133066299
Variable.5458      0.0069333333
Variable.5462      0.0000000000
Variable.5469      0.0397727228
Variable.5482      0.0379978355
Variable.5486      0.0880001001
Variable.5489      0.0416650848
Variable.5496      0.0218512891
Variable.5497      0.0301762826
Variable.5503      0.0280939413
Variable.5515      0.0106024131
Variable.5522      0.0521112742
Variable.5525      0.0276314922
Variable.5527      0.0009272727
Variable.5528      0.0122666667
Variable.5529      0.0067339130
Variable.5535      0.0000000000
Variable.5547      0.0131469496
Variable.5553      0.0035000000
Variable.5554      0.0165039070
Variable.5571      0.0069333333
Variable.5578      0.0067021041
Variable.5583      0.0087272727
Variable.5586      0.0235451600
Variable.5595      0.0092238095
Variable.5603      0.0065454545
Variable.5619      0.0075555556
Variable.5621      0.0315581961
Variable.5631      0.0000000000
Variable.5638      0.0212990494
Variable.5641      0.0141602564
Variable.5670      0.0000000000
Variable.5675      0.0264632425
Variable.5679      0.0000000000
Variable.5684      0.0327189639
Variable.5700      0.0405682126
Variable.5728      0.0060000000
Variable.5744      0.0333482437
Variable.5754      0.0000000000
Variable.5758      0.0188684149
Variable.5762      0.0030000000
Variable.5770      0.0000000000
Variable.5784      0.0554798856
Variable.5796      0.0820921566
Variable.5801      0.0000000000
Variable.5802      0.0859153169
Variable.5805      0.0087272727
Variable.5811      0.0547332892
Variable.5817      0.0264468864
Variable.5844      0.0038666667
Variable.5856      0.0155955103
Variable.5858      0.0094065934
Variable.5867      0.0527248086
Variable.5868      0.0000000000
Variable.5886      0.0000000000
Variable.5896      0.0238252402
Variable.5908      0.0643247131
Variable.5913      0.0035986395
Variable.5914      0.0304832331
Variable.5922      0.0534897999
Variable.5923      0.0030000000
Variable.5935      0.0062500000
Variable.5965      0.0115041703
Variable.5984      0.0160282481
Variable.5992      0.0293926975
Variable.6004      0.0069437229
Variable.6026      0.0106236737
Variable.6034      0.0069230769
Variable.6038      0.0266829992
Variable.6049      0.0018750000
Variable.6053      0.0000000000
Variable.6058      0.0644344258
Variable.6063      0.0000000000
Variable.6072      0.0066149871
Variable.6094      0.0381732396
Variable.6097      0.0073083004
Variable.6101      0.0325412630
Variable.6126      0.1447077840
Variable.6132      0.0282753367
Variable.6134      0.0134984985
Variable.6136      0.0000000000
Variable.6140      0.0564569295
Variable.6144      0.0719040558
Variable.6145      0.0035219512
Variable.6153      0.0085490196
Variable.6157      0.0595386116
Variable.6169      0.0000000000
Variable.6171      0.0113585586
Variable.6172      0.0000000000
Variable.6180      0.0476251680
Variable.6182      0.0343833803
Variable.6190      0.0000000000
Variable.6192      0.0000000000
Variable.6199      0.0202051282
Variable.6204      0.0780912149
Variable.6215      0.1424347520
Variable.6217      0.0222468764
Variable.6218      0.0501757811
Variable.6231      0.0243568510
Variable.6243      0.0066818182
Variable.6244      0.0399115514
Variable.6247      0.0000000000
Variable.6248      0.0000000000
Variable.6251      0.0166920227
Variable.6263      0.0100404040
Variable.6266      0.0411294088
Variable.6269      0.0248690890
Variable.6280      0.0000000000
Variable.6291      0.0038461538
Variable.6307      0.0928676217
Variable.6311      0.0128571429
Variable.6319      0.0000000000
Variable.6328      0.0451967851
Variable.6336      0.0672084277
Variable.6343      0.0039130435
Variable.6344      0.0074482759
Variable.6348      0.0786464356
Variable.6352      0.0038333333
Variable.6357      0.0133077528
Variable.6358      0.1035798275
Variable.6361      0.0000000000
Variable.6367      0.0147629870
Variable.6375      0.0535056524
Variable.6380      0.0092409524
Variable.6386      0.0000000000
Variable.6396      0.0487544199
Variable.6399      0.0018918919
Variable.6404      0.0000000000
Variable.6406      0.0125714286
Variable.6412      0.0998433735
Variable.6437      0.0038095238
Variable.6442      0.2350148829
Variable.6443      0.0038571429
Variable.6444      0.0000000000
Variable.6470      0.0171838095
Variable.6481      0.5488563189
Variable.6487      0.0377161496
Variable.6502      0.0000000000
Variable.6503      0.0290230952
Variable.6508      0.0037500000
Variable.6510      0.0232067094
Variable.6511      0.0489278158
Variable.6521      0.0128989627
Variable.6532      0.0100000000
Variable.6535      0.0063157895
Variable.6562      0.0039000000
Variable.6565      0.0135656315
Variable.6576      0.0177350649
Variable.6580      0.0000000000
Variable.6591      0.0000000000
Variable.6593      0.0000000000
Variable.6594      0.0202548737
Variable.6596      0.0047388027
Variable.6601      0.0116296296
Variable.6602      0.0026666667
Variable.6607      0.0202693906
Variable.6610      0.0373578672
Variable.6631      0.0026666667
Variable.6637      0.0222564920
Variable.6639      0.0425959117
Variable.6658      0.0219350215
Variable.6659      0.0020000000
Variable.6665      0.0685805372
Variable.6680      0.0051717172
Variable.6696      0.1118997972
Variable.6697      0.0000000000
Variable.6700      0.0038518519
Variable.6709      0.0035555556
Variable.6746      0.0207607143
Variable.6748      0.0188775068
Variable.6751      0.0000000000
Variable.6752      0.0195285661
Variable.6755      0.0020000000
Variable.6756      0.0423485301
Variable.6758      0.0165494949
Variable.6775      0.0057142857
Variable.6790      0.0067500000
Variable.6800      0.0198198198
Variable.6809      0.0048000000
Variable.6813      0.0124374057
Variable.6815      0.0203249255
Variable.6817      0.0098742857
Variable.6825      0.1111172433
Variable.6842      0.0219053409
Variable.6844      0.0033333333
Variable.6877      0.0065185185
Variable.6882      0.0419385659
Variable.6883      0.0017681159
Variable.6887      0.0742918354
Variable.6888      0.1133991522
Variable.6896      0.0037166086
Variable.6906      0.0000000000
Variable.6908      0.0530045788
Variable.6913      0.0369735109
Variable.6914      0.0175213629
Variable.6917      0.0061873327
Variable.6919      0.0336682828
Variable.6924      0.0354054291
Variable.6933      0.0132121212
Variable.6934      0.0453496961
Variable.6942      0.0743412684
Variable.6944      0.0000000000
Variable.6963      0.0147343847
Variable.6966      0.0000000000
Variable.6969      0.0000000000
Variable.6974      0.0596812140
Variable.6975      0.0258295135
Variable.6980      0.0000000000
Variable.6985      0.0873296025
Variable.6993      0.0246428571
Variable.7030      0.0352628818
Variable.7038      0.0361836998
Variable.7057      0.0731648799
Variable.7074      0.0326464748
Variable.7075      0.0733196401
Variable.7094      0.0213515152
Variable.7098      0.0056666667
Variable.7112      0.0160609142
Variable.7120      0.0382824165
Variable.7136      0.0420237348
Variable.7142      0.0335794914
Variable.7143      0.0071666667
Variable.7147      0.0890936440
Variable.7174      0.0125261984
Variable.7185      0.0600549728
Variable.7188      0.1083755629
Variable.7196      0.0648558939
Variable.7199      0.0831793803
Variable.7211      0.0746791407
Variable.7217      0.0145192308
Variable.7229      0.0000000000
Variable.7232      0.0826121745
Variable.7238      0.0287074592
Variable.7242      0.0536621743
Variable.7250      0.0326204279
Variable.7263      0.0243000000
Variable.7275      0.0189000000
Variable.7276      0.0036923077
Variable.7284      0.0039166667
Variable.7305      0.0020000000
Variable.7308      0.0035000000
Variable.7322      0.0218597987
Variable.7341      0.0131157495
Variable.7344      0.0000000000
Variable.7345      0.0186928105
Variable.7358      0.0262279202
Variable.7378      0.0695012047
Variable.7386      0.0065454545
Variable.7396      0.0711713057
Variable.7401      0.0091774359
Variable.7410      0.0191776557
Variable.7414      0.0124291791
Variable.7441      0.0065376344
Variable.7446      0.0206124050
Variable.7447      0.0567455991
Variable.7462      0.0177000000
Variable.7466      0.0337404049
Variable.7481      0.0203688495
Variable.7486      0.0000000000
Variable.7494      0.0662961361
Variable.7508      0.0000000000
Variable.7515      0.0474948887
Variable.7525      0.0150810252
Variable.7532      0.0265078489
Variable.7562      0.0299568800
Variable.7564      0.1595051939
Variable.7569      0.0840411443
Variable.7579      0.1217874040
Variable.7586      0.0358722378
Variable.7594      0.0125581395
Variable.7602      0.0316826647
Variable.7628      0.1170298339
Variable.7631      0.0039047619
Variable.7648      0.0109844386
Variable.7659      0.0411206748
Variable.7719      0.0681386179
Variable.7732      0.0179033862
Variable.7734      0.0814702975
Variable.7735      0.0868159084
Variable.7767      0.0032000000
Variable.7801      0.0099090909
Variable.7803      0.0289786506
Variable.7806      0.0148780922
Variable.7819      0.0170709382
Variable.7833      0.0000000000
Variable.7852      0.0209082295
Variable.7856      0.1346997412
Variable.7859      0.0065454545
Variable.7868      0.0819855083
Variable.7884      0.0278740159
Variable.7888      0.0261752137
Variable.7889      0.0000000000
Variable.7891      0.0273131313
Variable.7908      0.2448995357
Variable.7939      0.0110000000
Variable.7954      0.0104347826
Variable.7986      0.0043636364
Variable.7995      0.0712780239
Variable.7998      0.0348720651
Variable.8001      0.0263699705
Variable.8002      0.0992228313
Variable.8014      0.0143198265
Variable.8015      0.0328243330
Variable.8017      0.0296154810
Variable.8033      0.0000000000
Variable.8036      0.0181465310
Variable.8051      0.1022468741
Variable.8057      0.0368810597
Variable.8063      0.0381768368
Variable.8071      0.1556932531
Variable.8084      0.0279723170
Variable.8088      0.1575571189
Variable.8090      0.0000000000
Variable.8114      0.0573667754
Variable.8117      0.0248666155
Variable.8121      0.0092307692
Variable.8128      0.0039420290
Variable.8131      0.0236370495
Variable.8145      0.0098260870
Variable.8160      0.0030000000
Variable.8199      0.0599696140
Variable.8200      0.1100661512
Variable.8221      0.0265810858
Variable.8243      0.0033333333
Variable.8247      0.0369870130
Variable.8263      0.0036870555
Variable.8272      0.0074090909
Variable.8281      0.0471848839
Variable.8290      0.1300183759
Variable.8291      0.0381185354
Variable.8302      0.0326320346
Variable.8322      0.0317867319
Variable.8329      0.0684854565
Variable.8331      0.0308355185
Variable.8345      0.0036363636
Variable.8348      0.0112322069
Variable.8355      0.0295964944
Variable.8356      0.0039000000
Variable.8360      0.0839172220
Variable.8367      0.0128307692
Variable.8368      0.1887236972
Variable.8388      0.1139434662
Variable.8405      0.0396934218
Variable.8422      0.0699521856
Variable.8432      0.0065000000
Variable.8436      0.0220121212
Variable.8437      0.0264451033
Variable.8446      0.0886477085
Variable.8464      0.0375295056
Variable.8495      0.0137428571
Variable.8507      0.0066698413
Variable.8508      0.0793622587
Variable.8515      0.0242060523
Variable.8519      0.0884884945
Variable.8521      0.0335564810
Variable.8523      0.0465088259
Variable.8534      0.0026666667
Variable.8548      0.0028666667
Variable.8551      0.0461797268
Variable.8572      0.0037166086
Variable.8585      0.0893549611
Variable.8590      0.0088888889
Variable.8598      0.0480083749
Variable.8639      0.0000000000
Variable.8645      0.0000000000
Variable.8653      0.1078427842
Variable.8660      0.0408748658
Variable.8685      0.0451135826
Variable.8704      0.0169272727
Variable.8709      0.0279342295
Variable.8711      0.0179582543
Variable.8717      0.0189356774
Variable.8721      0.0240954991
Variable.8722      0.0000000000
Variable.8730      0.0937400155
Variable.8732      0.0607919641
Variable.8733      0.0277202941
Variable.8736      0.0036363636
Variable.8772      0.0473356334
Variable.8795      0.0412711580
Variable.8798      0.0000000000
Variable.8810      0.1052714402
Variable.8811      0.0020000000
Variable.8816      0.0149047619
Variable.8827      0.0469488171
Variable.8850      0.0311949593
Variable.8852      0.0914045121
Variable.8858      0.0026666667
Variable.8861      0.0040606061
Variable.8872      0.0070000000
Variable.8884      0.0476550457
Variable.8896      0.0172743804
Variable.8902      0.0119474313
Variable.8903      0.0000000000
Variable.8936      0.0342036444
Variable.8942      0.0363470250
Variable.8953      0.0763753888
Variable.8966      0.0000000000
Variable.8977      0.0436502645
Variable.8994      0.0141333333
Variable.9031      0.0469872232
Variable.9043      0.0189856185
Variable.9071      0.0289156842
Variable.9074      0.0218473763
Variable.9088      0.0528474383
Variable.9092      0.0193951763
Variable.9093      0.0270144599
Variable.9129      0.0189664014
Variable.9135      0.0266347141
Variable.9156      0.0441461775
Variable.9180      0.0283227115
Variable.9183      0.0291585363
Variable.9190      0.0482462374
Variable.9198      0.0554126722
Variable.9211      0.0359568843
Variable.9238      0.1464192820
Variable.9250      0.0075294118
Variable.9262      0.0221302874
Variable.9268      0.0845422441
Variable.9273      0.0071594203
Variable.9297      0.0000000000
Variable.9327      0.0142769231
Variable.9347      0.0000000000
Variable.9356      0.0060000000
Variable.9362      0.0293787115
Variable.9393      0.0349031485
Variable.9408      0.0922877702
Variable.9417      0.0000000000
Variable.9426      0.1521478254
Variable.9432      0.0458596581
Variable.9436      0.0037097561
Variable.9447      0.0928477986
Variable.9449      0.1112938512
Variable.9451      0.0034285714
Variable.9453      0.0576537945
Variable.9463      0.0069333333
Variable.9479      0.0000000000
Variable.9483      0.0053333333
Variable.9492      0.0026666667
Variable.9493      0.0688594869
Variable.9499      0.0000000000
Variable.9513      0.0037500000
Variable.9517      0.0101038772
Variable.9534      0.0019111111
Variable.9546      0.0000000000
Variable.9549      0.0213988086
Variable.9581      0.0065454545
Variable.9587      0.0534879829
Variable.9594      0.0124806031
Variable.9603      0.0176208488
Variable.9617      0.1452001864
Variable.9636      0.0070550370
Variable.9639      0.0000000000
Variable.9642      0.2033663540
Variable.9648      0.0105161725
Variable.9651      0.0019272727
Variable.9655      0.0261851504
Variable.9660      0.0799852418
Variable.9661      0.0129605083
Variable.9689      0.0131076923
Variable.9695      0.0138071429
Variable.9708      0.0161379310
Variable.9716      0.0036923077
Variable.9722      0.0348065017
Variable.9726      0.0315898396
Variable.9741      0.0238888575
Variable.9750      0.0163784579
Variable.9769      0.0161678531
Variable.9779      0.0553481104
Variable.9780      0.0063684211
Variable.9791      0.0639662265
Variable.9819      0.0000000000
Variable.9820      0.1016699290
Variable.9821      0.0387086920
Variable.9822      0.0351532382
Variable.9833      0.0314798916
Variable.9843      0.0076682616
Variable.9850      0.2059141155
Variable.9861      0.0443665485
Variable.9870      0.1747611283
Variable.9872      0.0475695659
Variable.9873      0.0122720146
Variable.9878      0.0000000000
Variable.9879      0.0036541353
Variable.9887      0.0127307692
Variable.9910      0.0282259207
Variable.9917      0.0803662711
Variable.9950      0.0130484472
Variable.9952      0.0394176139
Variable.9954      0.0000000000
Variable.9971      0.0097187879
Variable.9985      0.0136524674
Variable.9986      0.1545083516
Variable.9999      0.0248471178
Variable.7218      0.0000000000
Variable.7209      0.0104401914
Variable.2014      0.0521290103
Variable.8591      0.0457165238
Variable.1372      0.0458402301
Variable.7876      0.0458751055
Variable.749       0.0035555556
Variable.314       0.0351455628
Variable.3184      0.0000000000
Variable.9498      0.0180081293
Variable.2318      0.0381714310
Variable.6711      0.0209924232
Variable.9458      0.0387262094
Variable.860       0.0000000000
Variable.4676      0.0000000000
Variable.3426      0.0225681965
Variable.6561      0.0151435897
Variable.5998      0.0074074074
Variable.4076      0.0037500000
Variable.3609      0.0104298413
Variable.989       0.0108724528
Variable.4460      0.0058461538
Variable.3514      0.0135511441
Variable.2848      0.0030000000
Variable.3704      0.0000000000
Variable.5494      0.0000000000
Variable.4206      0.0075084175
Variable.8510      0.0039047619
Variable.7146      0.0000000000
Variable.9277      0.0000000000
Variable.3502      0.0032000000
Variable.3144      0.0407563550
Variable.1963      0.0217179487
Variable.5075      0.0035555556
Variable.3135      0.0000000000
Variable.4264      0.0000000000
Variable.2255      0.0000000000
Variable.780       0.0000000000
Variable.7056      0.0000000000
Variable.510       0.0325834869
Variable.9281      0.0000000000
Variable.2032      0.0303630080
Variable.8765      0.0066928105
Variable.5646      0.0230448796
Variable.2367      0.0170016543
Variable.8318      0.0039322034
Variable.4894      0.0000000000
Variable.6410      0.0038095238
Variable.2837      0.0271969442
Variable.6064      0.0109791754
Variable.9982      0.0080083333
Variable.1346      0.0071911330
Variable.1703      0.0000000000
Variable.2617      0.0437486558
Variable.7934      0.0147625418
Variable.8241      0.0107032967
Variable.4915      0.0000000000
Variable.2454      0.0632372851
Variable.7854      0.0307022385
Variable.8372      0.0173720365
Variable.2535      0.0000000000
Variable.4159      0.0000000000
Variable.5645      0.0112355885
Variable.5798      0.0292155172
Variable.1583      0.0083939394
Variable.4681      0.0000000000
Variable.5604      0.0066442688
Variable.731       0.0313290084
Variable.4398      0.0084754413
Variable.1605      0.0203419355
Variable.8945      0.0267505303
Variable.8699      0.0275720367
Variable.7195      0.0202940541
Variable.9691      0.0098072197
Variable.9434      0.0133392713
Variable.8366      0.0000000000
Variable.1662      0.0026666667
Variable.5989      0.0038571429
Variable.5148      0.0477654287
Variable.7823      0.0950231581
Variable.9805      0.0156043217
Variable.8870      0.0492105067
Variable.7573      0.0339662969
Variable.2102      0.0181834008
Variable.9646      0.0368179254
Variable.1327      0.0034285714
Variable.393       0.0000000000
Variable.761       0.0399297059
Variable.1380      0.0183146997
Variable.920       0.0484385722
Variable.2002      0.0139362532
Variable.928       0.0415011070
Variable.5479      0.0000000000
Variable.9255      0.0000000000
Variable.8824      0.0000000000
Variable.1518      0.0500102147
Variable.112       0.0244461768
Variable.5327      0.0000000000
Variable.5484      0.0000000000
Variable.7607      0.0219232228
Variable.5660      0.0112644689
Variable.1843      0.0228335671
Variable.7700      0.0067418182
Variable.8068      0.0347120230
Variable.7598      0.0294154762
Variable.5143      0.0000000000
Variable.543       0.0130746032
Variable.5725      0.0000000000
Variable.2516      0.0182807018
Variable.6668      0.0075111193
Variable.6828      0.0427892623
Variable.7165      0.0196890938
Variable.320       0.0446783240
Variable.7493      0.0468301278
Variable.7707      0.0066666667
Variable.1607      0.0038947368
Variable.4         0.0078488414
Variable.1627      0.0071413127
Variable.2127      0.0398970917
Variable.4688      0.0036666667
Variable.8504      0.0000000000
Variable.2646      0.0216984678
Variable.9747      0.0039230769
Variable.7900      0.0237096774
Variable.903       0.0122807018
Variable.2831      0.0567183677
Variable.2440      0.0237785548
Variable.7477      0.0000000000
Variable.9216      0.0037777778
Variable.4233      0.0000000000
Variable.8222      0.0000000000
Variable.4280      0.0435800000
Variable.169       0.0036363636
Variable.8065      0.0037410628
Variable.2244      0.0012533333
Variable.2794      0.0114938489
Variable.6691      0.0190571011
Variable.8333      0.0000000000
Variable.7621      0.0240657966
Variable.7919      0.0185059289
Variable.9537      0.0081111111
Variable.645       0.0065454545
Variable.1735      0.0000000000
Variable.4878      0.0235971480
Variable.8599      0.0120352941
Variable.405       0.0000000000
Variable.1606      0.0185135387
Variable.222       0.0088330435
Variable.9315      0.0381606765
Variable.1453      0.0000000000
Variable.9997      0.0338363856
Variable.7037      0.0000000000
Variable.8522      0.0240691350
Variable.5952      0.0260321768
Variable.7061      0.0120333333
Variable.4214      0.0084000000
Variable.1013      0.0099739096
Variable.1364      0.0034285714
Variable.8404      0.0153675889
Variable.10        0.0072052632
Variable.9981      0.0068571429
Variable.2457      0.0000000000
Variable.4751      0.0202857143
Variable.9308      0.0000000000
Variable.4737      0.0036923077
Variable.5957      0.0209794872
Variable.8111      0.0157090909
Variable.368       0.0058260870
Variable.6109      0.0479211033
Variable.1561      0.0053333333
Variable.7611      0.0095238095
Variable.9924      0.0138915616
Variable.6515      0.0344399708
Variable.5381      0.0034714715
Variable.8319      0.0073861237
Variable.2269      0.0000000000
Variable.2604      0.0087543424
Variable.5076      0.0038947368
Variable.1881      0.0038571429
Variable.6161      0.0697419010
Variable.4520      0.0000000000
Variable.7328      0.0048000000
Variable.8499      0.0121054301
Variable.4882      0.0200609319
Variable.5642      0.0117823944
Variable.592       0.0035000000
Variable.4535      0.0189604820
Variable.8662      0.0000000000
Variable.5931      0.0000000000
Variable.7839      0.0128571429
Variable.6968      0.0313434221
Variable.7931      0.0000000000
Variable.9481      0.0000000000
Variable.2316      0.0033333333
Variable.8681      0.0228127677
Variable.4927      0.0412789478
Variable.2273      0.0038750000
Variable.8793      0.0094285714
Variable.1296      0.0062222222
Variable.6478      0.0066401515
Variable.4629      0.0000000000
Variable.5523      0.0125287356
Variable.5918      0.0119797101
Variable.9700      0.0066666667
Variable.8549      0.0251633829
Variable.8443      0.0071140963
Variable.309       0.0080666667
Variable.296       0.0000000000
Variable.781       0.0159733333
Variable.3611      0.0072509804
Variable.7371      0.0038181818
Variable.1946      0.0266102451
Variable.2485      0.0395169965
Variable.1333      0.0036401515
Variable.9577      0.0071061783
Variable.6653      0.0192083710
Variable.8557      0.0000000000
Variable.2494      0.0026666667
Variable.7840      0.0000000000
Variable.5644      0.0140952381
Variable.7226      0.0000000000
Variable.2762      0.0160350140
Variable.7264      0.0000000000
Variable.6099      0.0074312169
Variable.5939      0.0000000000
Variable.5537      0.0081167100
Variable.4855      0.0289151793
Variable.2443      0.0036363636
Variable.8512      0.0098823529
Variable.8817      0.0000000000
Variable.796       0.0244126469
Variable.5920      0.0000000000
Variable.5383      0.0505479624
Variable.1179      0.0000000000
Variable.2346      0.0507259513
Variable.111       0.0033333333
Variable.4859      0.0429484062
Variable.2070      0.0190550708
Variable.7392      0.0321544929
Variable.8047      0.0060000000
Variable.7043      0.0180947811
Variable.9162      0.0112527290
Variable.2969      0.0053333333
Variable.8940      0.0353834838
Variable.3173      0.0036000000
Variable.6806      0.0000000000
Variable.3086      0.0000000000
Variable.7665      0.0226669521
Variable.55        0.0000000000
Variable.9714      0.0523597747
Variable.8361      0.0864555556
Variable.6369      0.0034285714
Variable.5121      0.0080000000
Variable.9638      0.0000000000
Variable.1324      0.0204679487
Variable.1998      0.0000000000
Variable.2937      0.0038857143
Variable.5574      0.0279463623
Variable.6304      0.0337113364
Variable.9956      0.0393744886
Variable.3242      0.1038626021
Variable.7130      0.0292456993
Variable.3916      0.0000000000
Variable.5657      0.0000000000
Variable.2703      0.0073969512
Variable.9301      0.0146666667
Variable.60        0.0032000000
Variable.7316      0.0162146032
Variable.9735      0.0329669365
Variable.5587      0.0000000000
Variable.4439      0.0000000000
Variable.1665      0.0066620690
Variable.4573      0.0241435407
Variable.6080      0.0310039784
Variable.7940      0.0901877182
Variable.8165      0.0072880751
Variable.4288      0.0276344916
Variable.1940      0.0288436975
Variable.3589      0.0237384615
Variable.5928      0.0000000000
Variable.3411      0.0164859802
Variable.4604      0.0038947368
Variable.4424      0.0050000000
Variable.5331      0.0163153463
Variable.6826      0.0037750363
Variable.1319      0.0334599399
Variable.3819      0.0088438596
Variable.8403      0.0262515219
Variable.8933      0.0000000000
Variable.9505      0.0000000000
Variable.9017      0.0072727273
Variable.7089      0.0039024390
Variable.1681      0.0817176722
Variable.9274      0.0067739096
Variable.6480      0.0098255639
Variable.5055      0.0000000000
Variable.620       0.0135943134
Variable.2899      0.0156918608
Variable.2830      0.0093974359
Variable.2872      0.0084190981
Variable.7485      0.0250864206
Variable.151       0.0037142857
Variable.9015      0.0102906404
Variable.3023      0.0000000000
Variable.7698      0.0066540659
Variable.4543      0.0053333333
Variable.9477      0.0201009361
Variable.7645      0.1061675245
Variable.8303      0.0157555556
Variable.6636      0.0101684211
Variable.888       0.0091177394
Variable.6625      0.0255574922
Variable.4617      0.0421866614
Variable.241       0.0423328031
Variable.2435      0.1434374298
Variable.9682      0.0040000000
Variable.5871      0.0240867362
Variable.4826      0.0000000000
Variable.273       0.0317371327
Variable.3581      0.0106279070
Variable.4660      0.0026666667
Variable.6103      0.0000000000
Variable.2028      0.0000000000
Variable.666       0.0223271709
Variable.1124      0.0026666667
Variable.2194      0.0048333333
Variable.3217      0.0000000000
Variable.6501      0.0126354199
Variable.7790      0.0000000000
Variable.3148      0.0053667263
Variable.4689      0.0000000000
Variable.3724      0.0036666667
Variable.3722      0.0000000000
Variable.578       0.0035789474
Variable.1301      0.0020000000
Variable.2900      0.0131566952
Variable.8752      0.0000000000
Variable.7153      0.0126176471
Variable.8822      0.0000000000
Variable.1626      0.0069807692
Variable.6721      0.0262544298
Variable.7996      0.0000000000
Variable.6979      0.0210245374
Variable.9770      0.0259110099
Variable.3397      0.0040272109
Variable.3388      0.0038461538
Variable.7350      0.0394569027
Variable.4605      0.0141025641
Variable.7186      0.0084000000
Variable.1951      0.0442489536
Variable.7765      0.0094945055
Variable.1774      0.0348580720
Variable.2453      0.0038571429
Variable.958       0.0291242481
Variable.2473      0.0035555556
Variable.7786      0.0032000000
Variable.3254      0.0161711230
Variable.482       0.0137402597
Variable.8310      0.0000000000
Variable.9612      0.0216255378
Variable.8426      0.0036352201
Variable.3044      0.0026666667
Variable.5572      0.0038787879
Variable.2787      0.0000000000
Variable.7187      0.0356714286
Variable.4771      0.0341738135
Variable.2331      0.0162666667
Variable.2897      0.0000000000
Variable.8785      0.0157769827
Variable.3203      0.0030000000
Variable.7009      0.0080000000
Variable.7019      0.0592663953
Variable.5421      0.0595997917
Variable.1371      0.0249861169
Variable.5892      0.0153499419
Variable.8869      0.0038000000
Variable.7994      0.0450003775
Variable.4357      0.0088888889
Variable.3475      0.0136225056
Variable.1893      0.0105363248
Variable.502       0.0216093713
Variable.10000     0.0191505839
Variable.2340      0.0036786787
Variable.2451      0.0262323180
Variable.9486      0.0047593220
Variable.342       0.0038518519
Variable.4498      0.0000000000
Variable.6689      0.0037293869
Variable.6704      0.0233713926
Variable.669       0.0268869812
Variable.799       0.0129947865
Variable.6167      0.0095238095
Variable.1751      0.0037647059
Variable.295       0.0284161597
Variable.1538      0.0000000000
Variable.6425      0.0000000000
Variable.9520      0.0000000000
Variable.4884      0.0764550960
Variable.102       0.0000000000
Variable.9957      0.0000000000
Variable.2632      0.0033333333
Variable.6225      0.0000000000
Variable.8518      0.0072214052
Variable.9669      0.0057142857
Variable.8332      0.0026666667
Variable.6090      0.0052000000
Variable.9834      0.0408504298
Variable.7962      0.0000000000
Variable.1522      0.0366432176
Variable.5981      0.0154915743
Variable.4694      0.0186414752
Variable.7777      0.0103433325
Variable.8992      0.0000000000
Variable.1450      0.0037333333
Variable.1439      0.0000000000
Variable.6765      0.0149041667
Variable.7495      0.0457740494
Variable.7110      0.0146190329
Variable.1244      0.0167349696
Variable.728       0.0000000000
Variable.7740      0.0115026574
Variable.2098      0.0610323140
Variable.8524      0.0020000000
Variable.6085      0.0324334905
Variable.8796      0.0000000000
Variable.231       0.0503466667
Variable.6530      0.0030000000
Variable.3943      0.0086363636
Variable.8773      0.0000000000
Variable.1160      0.0180099071
Variable.8723      0.0038000000
Variable.285       0.0110450355
Variable.969       0.0083478261
Variable.1705      0.0097678855
Variable.9528      0.0519536370
Variable.50        0.0000000000
Variable.2572      0.0035904255
Variable.3824      0.0000000000
Variable.6864      0.0099069767
Variable.834       0.0160201058
Variable.1657      0.0114000000
Variable.7357      0.0397354925
Variable.9593      0.0110837438
Variable.2687      0.0220039072
Variable.3341      0.0049333333
Variable.7825      0.0087601810
Variable.2530      0.0333631459
Variable.5371      0.0290527014
Variable.7156      0.0026666667
Variable.411       0.0000000000
Variable.6322      0.0107987327
Variable.3566      0.0104131274
Variable.4219      0.0034285714
Variable.711       0.0000000000
Variable.5453      0.0379500552
Variable.9350      0.0192642390
Variable.5878      0.0494313871
Variable.1716      0.0659389091
Variable.1630      0.0156800000
Variable.2832      0.0251399028
Variable.8173      0.0000000000
Variable.7606      0.0000000000
Variable.1939      0.0000000000
Variable.7666      0.0020000000
Variable.7526      0.0114636591
Variable.9389      0.0135000000
Variable.9784      0.0240534724
Variable.7420      0.0511883013
Variable.9590      0.0076403101
Variable.2526      0.0166434676
Variable.2056      0.0128571429
Variable.2134      0.0451645057
Variable.9756      0.0000000000
Variable.9011      0.0000000000
Variable.7499      0.0037090909
Variable.5386      0.0000000000
Variable.8883      0.0164471545
Variable.703       0.0061490196
Variable.811       0.0242772247
Variable.7524      0.0593006113
Variable.1336      0.0088704762
Variable.6858      0.0283983123
Variable.8692      0.0069166086
Variable.963       0.0000000000
Variable.28        0.0000000000
Variable.262       0.0038620690
Variable.9424      0.0000000000
Variable.8169      0.0147599023
Variable.3605      0.1875756426
Variable.90        0.0090206285
Variable.1245      0.0838346325
Variable.9127      0.0527180692
Variable.8423      0.0105087919
Variable.6436      0.0282820183
Variable.8906      0.0130769231
Variable.7521      0.0137169586
Variable.7871      0.0320958231
Variable.2329      0.0232523237
Variable.8152      0.0351748837
Variable.9293      0.0000000000
Variable.6411      0.0076710673
Variable.2380      0.0000000000
Variable.6469      0.0000000000
Variable.9027      0.0993484691
Variable.2275      0.0243219048
Variable.5558      0.0542931165
Variable.7148      0.0246643902
Variable.1108      0.0127715801
Variable.9311      0.0000000000
Variable.5176      0.0000000000
Variable.7853      0.0321870824
Variable.54        0.0110580313
Variable.8743      0.0030000000
Variable.7529      0.0380279149
Variable.6630      0.0183181593
Variable.1541      0.0038857143
Variable.7724      0.0026666667
Variable.7846      0.0274327216
Variable.133       0.0100744186
Variable.3020      0.0000000000
Variable.8213      0.0462883560
Variable.8489      0.0136474359
Variable.7235      0.0065333333
Variable.7372      0.0000000000
Variable.7855      0.0217262276
Variable.9688      0.0077043011
Variable.9512      0.0412790549
Variable.2960      0.0000000000
Variable.5838      0.0118603175
Variable.8866      0.0000000000
Variable.2067      0.0072444334
Variable.8359      0.0000000000
Variable.5017      0.0099444444
Variable.7637      0.0000000000
Variable.3305      0.0000000000
Variable.4843      0.0073620764
Variable.6224      0.0209256251
Variable.509       0.0511380117
Variable.394       0.0690915016
Variable.6188      0.0000000000
Variable.177       0.0106303098
Variable.7615      0.0000000000
Variable.1020      0.0074576293
Variable.3837      0.1183598165
Variable.9888      0.0662013549
Variable.8398      0.0000000000
Variable.1656      0.0000000000
Variable.1456      0.0404430997
Variable.9374      0.0572362071
Variable.4704      0.0000000000
Variable.1058      0.0098929424
Variable.7892      0.0404298990
Variable.7355      0.0098262626
Variable.4712      0.0000000000
Variable.8846      0.1031792450
Variable.1436      0.0130943748
Variable.2700      0.0352036337
Variable.4937      0.0050000000
Variable.360       0.0037662745
Variable.6040      0.0277454545
Variable.7673      0.0100636630
Variable.2033      0.0000000000
Variable.9680      0.0039259259
Variable.8818      0.0057894737
Variable.337       0.0189587302
Variable.2481      0.0366400000
Variable.91        0.0269739983
Variable.8983      0.0062222222
Variable.8305      0.0000000000
Variable.9415      0.0316366234
Variable.5734      0.0033333333
Variable.3927      0.0030000000
Variable.737       0.0130331691
Variable.9042      0.0136042288
Variable.6177      0.0030000000
Variable.770       0.0195993252
Variable.8304      0.0000000000
Variable.2843      0.0244357528
Variable.8275      0.0564388723
Variable.3917      0.0168669504
Variable.9991      0.0000000000
Variable.7474      0.0000000000
Variable.9407      0.0167286648
Variable.9522      0.0085333333
Variable.5134      0.0219363123
Variable.2311      0.0292159911
Variable.5324      0.0143963085
Variable.7861      0.0000000000
Variable.5056      0.0463289437
Variable.839       0.0039090909
Variable.181       0.0112038612
Variable.3921      0.0482185098
Variable.4388      0.0094789916
Variable.470       0.0030000000
Variable.3584      0.0177857143
Variable.9578      0.0131139122
Variable.7955      0.0113939394
Variable.486       0.0334127314
Variable.5031      0.0676531217
Variable.8865      0.0075428571
Variable.8855      0.0256608187
Variable.4365      0.0199431732
Variable.7349      0.0000000000
Variable.8995      0.0000000000
Variable.6507      0.0733949837
Variable.2173      0.0121904762
Variable.626       0.0106116279
Variable.5584      0.0018518519
Variable.9208      0.0000000000
Variable.6862      0.0000000000
Variable.8763      0.0000000000
Variable.1874      0.0000000000
Variable.4997      0.0060000000
Variable.5480      0.0122500000
Variable.9396      0.0000000000
Variable.5814      0.0039024390
Variable.4162      0.0650964510
Variable.3200      0.0191658380
Variable.376       0.0149074074
Variable.7646      0.1193231171
Variable.6388      0.0180538695
Variable.2285      0.0000000000
Variable.3262      0.0000000000
Variable.2029      0.0150116550
Variable.311       0.0223313285
Variable.6275      0.0172126984
Variable.7204      0.0075897436
Variable.4234      0.0466301112
Variable.1465      0.0116878307
Variable.6486      0.0079294574
Variable.6273      0.0033333333
Variable.779       0.0251601220
Variable.6915      0.0648718826
Variable.2651      0.1013181268
Variable.7654      0.0038709677
Variable.9148      0.0000000000
Variable.1999      0.0038750000
Variable.4562      0.0072000000
Variable.9402      0.0000000000
Variable.736       0.0000000000
Variable.7549      0.0000000000
Variable.3968      0.0000000000
Variable.6374      0.0068571429
Variable.5676      0.0101025641
Variable.9893      0.0180869078
Variable.4368      0.0346215075
Variable.7453      0.0190589081
Variable.554       0.0163441515
Variable.2393      0.0280893506
Variable.9413      0.0304725008
Variable.3913      0.1259074596
Variable.6814      0.0160303030
Variable.7688      0.0000000000
Variable.1629      0.0168317433
Variable.7558      0.0058363636
Variable.7248      0.0000000000
Variable.371       0.0096000000
Variable.2909      0.0037465310
Variable.8735      0.0151282051
Variable.4939      0.0038095238
Variable.5854      0.1034161747
Variable.9326      0.0244334029
Variable.1631      0.0246306208
Variable.657       0.0067602339
Variable.6514      0.0163746436
Variable.742       0.0074102564
Variable.3417      0.0000000000
Variable.1221      0.0112644689
Variable.544       0.0144400000
Variable.999       0.0038666667
Variable.8209      0.0000000000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">varImpPlot</span>(Model.random, <span class="at">main=</span><span class="st">"predicting class"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cancerwork_tree_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>According to the random forests, Variable.6481 is the most important factor, followed by Variable.2640 and Variable.4192, Variable.3986and Variable.471, Variable.2435and Variable.6215 are relatively unimportant.</p>
</section>
<section id="roc-and-auc-2" class="level4">
<h4 class="anchored" data-anchor-id="roc-and-auc-2">ROC and AUC:</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ROCR)</span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>pred.prob <span class="ot">&lt;-</span> <span class="fu">predict</span>(Model.random,<span class="at">newdata =</span> data_test,<span class="at">type =</span> <span class="st">"prob"</span>)[,<span class="dv">2</span>]</span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a>true_labels <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">as.character</span>(data_test<span class="sc">$</span>Class))</span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a>true_labels[true_labels <span class="sc">==</span> <span class="sc">-</span><span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb72-6"><a href="#cb72-6" aria-hidden="true" tabindex="-1"></a>score2 <span class="ot">&lt;-</span> <span class="fu">prediction</span>(pred.prob,true_labels)</span>
<span id="cb72-7"><a href="#cb72-7" aria-hidden="true" tabindex="-1"></a>perf2 <span class="ot">&lt;-</span> <span class="fu">performance</span>(score2,<span class="st">"tpr"</span>,<span class="st">"fpr"</span>)</span>
<span id="cb72-8"><a href="#cb72-8" aria-hidden="true" tabindex="-1"></a>auc2 <span class="ot">&lt;-</span> <span class="fu">performance</span>(score2,<span class="st">"auc"</span>)</span>
<span id="cb72-9"><a href="#cb72-9" aria-hidden="true" tabindex="-1"></a>perfd2 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x=</span>perf2<span class="sc">@</span>x.values[<span class="dv">1</span>][[<span class="dv">1</span>]],<span class="at">y=</span>perf2<span class="sc">@</span>y.values[<span class="dv">1</span>][[<span class="dv">1</span>]])</span>
<span id="cb72-10"><a href="#cb72-10" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(perfd2,<span class="fu">aes</span>(<span class="at">x=</span>x,<span class="at">y=</span>y))<span class="sc">+</span><span class="fu">geom_line</span>()<span class="sc">+</span></span>
<span id="cb72-11"><a href="#cb72-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"False positive rate"</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">"True positive rate"</span>) <span class="sc">+</span></span>
<span id="cb72-12"><a href="#cb72-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="fu">paste</span>(<span class="st">"Area under the curve:"</span>, <span class="fu">round</span>(auc2<span class="sc">@</span>y.values[[<span class="dv">1</span>]], <span class="dv">3</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cancerwork_tree_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The ROC curve show the classification performance. A higher AUC(close to 1 ) indicates a better-performing model. The AUC of bagging forest is 0.911, which is greater than 0.5 and close to 1, show the classification effect is excellent.</p>
<p>Prediction:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>random.pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(Model.random,<span class="at">newdata =</span> data_test[,<span class="sc">-</span><span class="dv">1</span>],<span class="at">type=</span><span class="st">"class"</span>) </span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>test.table.random <span class="ot">&lt;-</span> <span class="fu">table</span>(data_test[,<span class="dv">1</span>],random.pred) </span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(test.table.random) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   random.pred
     0  1
  0 45 11
  1  8 36</code></pre>
</div>
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>accuracy <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">diag</span>(test.table.random))<span class="sc">/</span><span class="fu">sum</span>(test.table.random) </span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(accuracy)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.81</code></pre>
</div>
</div>
<p>After the predict of the test set, obtained the Confusion Matrix and the Accuracy. The Accuracy of test set is 0.81, which is good. The bagging forest model has good classification ability.</p>

</section>
</section>
</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-week4_tree_based" class="csl-entry" role="listitem">
Instructor, Course. 2025. <span>“Week 4: Tree-Based Methods (Excluding Solution).”</span> Online Course Material. <a href="https://moodle.gla.ac.uk/pluginfile.php/8303767/mod_resource/content/10/Week4-Tree-based%20methods%20%28excl.%20solution%29.pdf">https://moodle.gla.ac.uk/pluginfile.php/8303767/mod_resource/content/10/Week4-Tree-based%20methods%20%28excl.%20solution%29.pdf</a>.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>